### ISSUE TITLE
F-Droid build failed

### ISSUE THREAD

**Issue by linsui** [Iamlooker/Droid-ify#1]
A RC version of the gradle is used which is not allowed because the source code may be not available. Can we use Gradle 7.4? Thanks!

**Comment by Iamlooker** [comment]
Sure I will update the gradle version ☺️

**Comment by Iamlooker** [comment]
Is the build in progress?

**Comment by linsui** [comment]
It has been published.

**Comment by Iamlooker** [comment]
I don't think FDroid build is in progress. Just letting you know

**Comment by linsui** [comment]
https://gitlab.com/fdroid/fdroiddata/-/merge_requests/11666
