### ISSUE TITLE
Redesigned screenshots section

### ISSUE THREAD

**Issue by Donkey-Doug** [Iamlooker/Droid-ify#10]
Place the screenshot section directly under the install button and do not make it collapsable, similar to the play store. Make the thumbnails/previews scrollable from left to right and do not cut them into squares:

![play-store-material-theme_1](https://user-images.githubusercontent.com/50382414/136286191-78b2a21e-97d7-464c-bd68-845eb2e7be53.jpg)

Notice the previews, which are not square, and have rounded corners that are consistent with the rest of the UI:

![e-material-theme-redesign-10](https://user-images.githubusercontent.com/50382414/136287151-c80f8e62-729a-47ab-9f3b-34ad95af5ea7.png)

**Comment by Donkey-Doug** [comment]
Screenshots are usually the first thing people look at, so placing them up top makes sense in my opinion.

**Comment by Donkey-Doug** [comment]
Please at least make the screenshot section carousel style instead of the current grid.

**Comment by Iamlooker** [comment]
Fixed with ba0b070988c4aa08fddcfd31e38c27b484d40eb0
