### ISSUE TITLE
Weblate: Could not push the repository

### ISSUE THREAD

**Issue by coxde** [Iamlooker/Droid-ify#100]
It seems to be unable to translate because of [this](https://hosted.weblate.org/projects/droidify/localization/#alerts).

Weblate could not push changes to the upstream repository.

```
fatal: 'git@github.com/Iamlooker/Droid-ify.git' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
 (128)
```

**Comment by Iamlooker** [comment]
Ooh sed will fix it in a day. Sry for the inconvenience

**Comment by Iamlooker** [comment]
This has been fixed can you please try again

**Comment by coxde** [comment]
Working perfectly, thanks!

**Comment by Iamlooker** [comment]
😉
