### ISSUE TITLE
[Feature Request] Material You Theme

### ISSUE THREAD

**Issue by d35r0n** [Iamlooker/Droid-ify#100]
It would be pretty awesome if you could add Material You theme to the app. Your app's UI is pretty dope and it would definitely match the color scheme of Material You.

**Comment by pc00per** [comment]
Agreed. But please don't migrate to Jetpack Compose. Work within the same toolkit currently you're in.
JC has some serious scroll issues under android animations disabled.

**Comment by Iamlooker** [comment]
Fixed in #204
