### ISSUE TITLE
unintentional tab switching while scrolling 

### ISSUE THREAD

**Issue by trsh3** [Iamlooker/Droid-ify#105]
Might just be a problem for me, but it happens a lot. When trying to scroll, the app thinks I swipe horizontally to change tabs. I don't have this problem in any other app. Would be great if the app could detect a scrolling movement, even if I'm not swiping perfectly vertical.

**Comment by vertigo220** [comment]
I actually think this is an Android problem, as I've been having it here and there in different apps for the past few years or so. Wasn't an issue, at least not that I noticed or remember, the first several years of Android use, but then somewhere along the way it started happening a fair bit. I've mentioned it in other apps before, though I don't remember which ones, but definitely seems to be widespread and not an issue with any one app specifically. I think the screen sensitivity is too high for the algorithms that Android uses to determine swipe direction, and the slightest bit of sideways direction in a scroll causes it to register as a sideways swipe. That said, maybe the app could adjust for this, but I seem to recall one of the apps I mentioned it with before, the dev said there was nothing that could be done.
