### ISSUE TITLE
App version in green

### ISSUE THREAD

**Issue by yephny** [Iamlooker/Droid-ify#109]
**Describe the bug**
In the first two app lists, the version number aligned to right appears to be green instead of white for some apps. This gets fixed when you open&close any app but some other apps get the green color this time.

**To Reproduce**
1. Scroll down in Available or Installed.
2. Check the version numbers.

**Expected behavior**
They all should be white.

**Screenshots**
![img](https://a.pomf.cat/zkxzbc.png)

**Smartphone:**
-Android 10, app v.0.3.5

**Comment by yephny** [comment]
The issue still persists in the "Installed" tab, though it's fixed for apps listed in "Available".

**Comment by Iamlooker** [comment]
> 

Weird I cant seem to replicate this and actually both of them uses same base so it shouldn't happen but will look into this

**Comment by yephny** [comment]
You may want to re-open the issue in case it's overlooked. ![Here's a screenshot from Droid-ify v.0.4.1.](https://a.pomf.cat/rnnimt.png)

**Comment by machiav3lli** [comment]
I think I know where the issue can be

**Comment by yephny** [comment]
Oops, it's still there even for apps in the Available tab. ![available](https://a.pomf.cat/bmbhum.png)
