### ISSUE TITLE
Material 3 and more

### ISSUE THREAD

**Issue by k2helix** [Iamlooker/Droid-ify#11]
Hello, thank you for creating this app, it looks and works flawlessly!

It would be nice to have the new Material 3 design, including the theme color. 

It would also be nice to have an option to enable relative or absolute dates (or even both), like "Updated x days ago/Updated 21/03/2021" like in the official F-droid app instead of having to look the latest version date. 

It is nice to see that the project is being updated recently, really

**Comment by jcperil** [comment]
I like the UI of Droid-ify 0.4.3. If Material design 3 is implemented, it should be opt-in that users can enable in the settings.

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
@k2helix, please separate this request and your request for modification of the format of dates, because although I like the new Material 3/You, I prefer absolute dates to relative dates.

**Comment by k2helix** [comment]
> @k2helix, please separate this request and your request for modification of the format of dates, because although I like the new Material 3/You, I prefer absolute dates to relative dates.

I see why it should be separated, but I'll just edit this one to request an option for relative/absolute dates instead of relative dates directly. I don't feel like creating another issue for that

**Comment by Iamlooker** [comment]
Material You have been added is available to test on telegram group. It will be available in 2 days or so
