### ISSUE TITLE
Make app descriptions gray in app list

### ISSUE THREAD

**Issue by yephny** [Iamlooker/Droid-ify#110]
**Is your feature request related to a problem? Please describe.**
Especially compared to Foxy, it's challenging to look at and figure out Droid-ify. Because everything is in the same color, it all looks the same like a continuous document instead of a list where apps are listed one by one.

**Describe the solution you'd like**
If the app description under each title is gray instead of white (as Amoled doesn't necessarily imply high contrast), this issue would be no more.

**Comment by Iamlooker** [comment]
Fixed in cf430988c0387bf972b32b75e716df579cd02045
