### ISSUE TITLE
Translate a component

### ISSUE THREAD

**Issue by gallegonovato** [Iamlooker/Droid-ify#112]
Good afternoon @Iamlooker 

I wanted to ask you if it would be possible to translate the Droid-ify application to the language it is in.  The categories that come out of the applications. 

Because translating all the content, as suggested in some other suggestion I do not know if it would be possible. Since each description is different, and I don't know if other apps in the fdroid store do it or not.

Best regards 

Pd: still still crashing the app colors with the Android button bar. And the cleaning part is missing without translation.

Pd: and I don't know if the app icon for Android 13: https://github.com/Iamlooker/Droid-ify/pull/91 . It could be put as main also for other systems. Or the one before https://www.apkmirror.com/wp-content/themes/APKMirror/ap_resize/ap_resize.php?src=https%3A%2F%2Fwww.apkmirror.com%2Fwp-content%2Fuploads%2F2022%2F06%2FDroid-ify_round.png&w=96&h=96&q=100 

Please do not take my words wrong. And please excuse me if I have said or done something wrong.

**Comment by Iamlooker** [comment]
Well actually some apps are localized in many languages, but Droid-ify currently only takes English results, I am working on getting localized data but there is still a lot of time left. You can't change language of other app's description in droidify for now. And that icon will be available in future updates, but I dont understand what you were trying to say 😅

**Comment by vertigo220** [comment]
What about integrating with Google Translate so an app's description can be automatically copied and sent to it for translation? It would take the user out of Droid-ify, but it would at least make it easy for them to read the descriptions.
