### ISSUE TITLE
Show indication in app list for installed appsb

### ISSUE THREAD

**Issue by vertigo220** [Iamlooker/Droid-ify#116]
When searching/browsing available apps, there's no indication in the list if an app is already installed. If an installed app needs an update, the version number is highlighted orange, but if it's up-to-date, there's nothing. I'd suggest highlighting the version number of installed, up-to-date apps green.

**Comment by Donkey-Doug** [comment]
I do not like this idea. It adds visual clutter. Also, no other store has this (google play, apple app store, ms store)

**Comment by vertigo220** [comment]
How exactly does it add visual clutter? The version number is already there, all this would do is add a highlight over it. Also:

![MS Store](https://user-images.githubusercontent.com/12024557/195958305-3189f74e-2449-481d-89e7-d616618e03ee.png)

![Play Store](https://user-images.githubusercontent.com/12024557/195958306-f3473144-c160-4344-8c49-1444470f648c.jpg)

**Comment by Farqu** [comment]
There is already an highlight for installed apps which have new versions available. Adding a highlight for installed but up-to-date apps is not too much clutter in my eyes, it would increase usability. I would like to see this as well.

![Screenshot_20221115-122517195_1](https://user-images.githubusercontent.com/20368606/201909696-f0309d57-61b1-454a-b88f-f5b75265a2e8.jpg)
