### ISSUE TITLE
Inconsistency regarding app versions

### ISSUE THREAD

**Issue by vertigo220** [Iamlooker/Droid-ify#117]
One of the apps I have installed showed updates available in Neo Store (image 1) but not in Droid-ify (image 2). Droid-ify shows the armeabi-v7a version installed (image 3) whereas Neo Store shows it as installed but shows the arm64 version as suggested (image 4), which I take as meaning recommended and seems correct to me. So if it truly is the recommended version for my device, Droid-ify should also indicate that and show it as an available update like Neo Store.

![Screenshot_20221004-191138_Neo Store](https://user-images.githubusercontent.com/12024557/194795436-26c64669-9b0c-47e3-9da3-9a6b9ab50bfc.jpg)

![Screenshot_20221004-191127_Droid-ify](https://user-images.githubusercontent.com/12024557/194795444-3868503c-c25a-41a1-8234-d4b42b123f2d.jpg)

![Screenshot_20221004-191109_Droid-ify](https://user-images.githubusercontent.com/12024557/194795452-c96e3208-7778-4330-9d96-1cff20bef743.jpg)

![Screenshot_20221004-191116_Neo Store](https://user-images.githubusercontent.com/12024557/194795458-8d2d821a-ee79-4714-b07b-4e4ec0e25490.jpg)

**Comment by Iamlooker** [comment]
The update is not visible because the repos are not synced, you can sync repos but clicking on "Sync" icon on tool bar in home screen.

And the reason because of which Droid-ify isn't showing a suggested version is because, it either shows a suggested version above the installed version or the installed version.

**Comment by vertigo220** [comment]
Maybe I'm misunderstanding, but that doesn't seem to be the problem. For one, all repos should have been synced, though of course there's no way to know now if they were. But second, Droid-ify _did_ show the same versions as Neo Store, indicating the repos were synced and up-to-date; it just was in disagreement with Neo Store as to which version should be installed.

**Comment by Iamlooker** [comment]
Droid-ify suggests update based on past installation. It looks to me as if the previous version was arm-v7 version, that's why we are not suggesting the arm-v8 version.
