### ISSUE TITLE
Relocate "ignore all new versions" to versions section

### ISSUE THREAD

**Issue by Donkey-Doug** [Iamlooker/Droid-ify#118]
![Screenshot_20221011-203307_Droid-ify](https://user-images.githubusercontent.com/50382414/195171907-7df9c846-d642-437e-8db5-d13ffd54c89e.png)

I think having it in a similar location makes more sense.

**Comment by vertigo220** [comment]
I would actually think it would make more sense being immediately under the update/install button, as well as the "Ignore this version" toggle. Either way, having it where it is, between the screenshots and app description, certainly doesn't seem like the best place for it.
