### ISSUE TITLE
Show translation percentage in selected locale

### ISSUE THREAD

**Issue by comradekingu** [Iamlooker/Droid-ify#118]
It would be nice to be able to see if a translation is available before installing an app.
Reasonably, the percentage of coverage in the user-selected locale is relevant.

Considered: Full list, ability to show only translated apps over 90%

**Comment by Iamlooker** [comment]
Well it would be cool without a doubt but kinda obselete at the same time.

Percent doesn't necessarily signifies the amount of app,
It just tells the number of words which maybe be different from the total amount of strings.

**Comment by comradekingu** [comment]
I was thinking percentage of translated strings (as different from source).
Never seen a string partly translated.
Short of normalizing for amount of words per string, you may fare better or worse below 100%, but that is mainly what people will be looking for.

**Comment by Iamlooker** [comment]
Plus weblate does word checks too and if they dail it count it as not translated
(e.g. word doesnt make sence like "Amoled" so it is untranslated)

**Comment by machiav3lli** [comment]
TODOs:
- [ ] Adding weblate widget to README
- [ ] Adding available languages to app description

**Comment by comradekingu** [comment]
>     * [ ]  Adding weblate widget to README

@machiav3lli Like so? #132

**Comment by machiav3lli** [comment]
Closed with #132 and #133, thanks @comradekingu
