### ISSUE TITLE
After updating to v0.4.0, Droid-ify keeps crashing while installing an app

### ISSUE THREAD

**Issue by soumyabratabose** [Iamlooker/Droid-ify#119]
![Screenshot_20211117-203419](https://user-images.githubusercontent.com/89439748/142225760-ec9941fd-4a6c-44ec-80ac-6fe2b8184642.png)

**Comment by Iamlooker** [comment]
Is silent install on?

**Comment by soumyabratabose** [comment]
Nope 
![Screenshot_20211117-203920](https://user-images.githubusercontent.com/89439748/142226525-057e4fa7-8513-4278-84e3-f9982a1da015.png)

**Comment by Iamlooker** [comment]
Fixed

**Comment by Iamlooker** [comment]
Release new one in few minutes

**Comment by Iamlooker** [comment]
Done v0.4.1 should Fix it
