### ISSUE TITLE
Remove text "Screenshots" from screenshot section

### ISSUE THREAD

**Issue by Donkey-Doug** [Iamlooker/Droid-ify#119]
Everybody can see the screenshots are screenshots. I think the text and drop down arrow should be removed.

**Comment by Jordan-Dixon** [comment]
Maybe replaced with a setting to either turn screenshots on or off?

**Comment by Donkey-Doug** [comment]
> Maybe replaced with a setting to either turn screenshots on or off?

Why? I see no reason to hide screenshots. No other store lets you do this. Not the play store, Apple app store, MS store, linux stores.

**Comment by Jordan-Dixon** [comment]
@Donkey-Doug well I think it is for a more compact look for people that just want to see the page and description. The bar that says screenshots is there to hide the screenshots so instead of getting rid of it altogether or keeping it, we could add a setting to turn it off.

**Comment by magnus-ISU** [comment]
I think a setting is a reasonable option. It seems unlikely to me that many people want screenshots for some apps but not others.

**Comment by magnus-ISU** [comment]
Should be done
