### ISSUE TITLE
Remove background of "source code" in header

### ISSUE THREAD

**Issue by Donkey-Doug** [Iamlooker/Droid-ify#124]
I think this is an oversight, because it looks weird and is honestly barely visible.

![Screenshot_20221014-221551_Droid-ify](https://user-images.githubusercontent.com/50382414/195934885-f2f1dc26-18a9-49f0-9f1b-f512e83845f1.png)

**Comment by magnus-ISU** [comment]
Do you mean the button? I like it (it implies it is pressable) and would be more important yet if/when I finish #73

**Comment by Donkey-Doug** [comment]
Let's continue the discussion in 73.
