### ISSUE TITLE
Header minor redesign

### ISSUE THREAD

**Issue by Donkey-Doug** [Iamlooker/Droid-ify#126]
This is what the header currently looks like:

![Screenshot_20221014-222508_Droid-ify](https://user-images.githubusercontent.com/50382414/195937398-e5941bb7-8ff4-4659-9997-097f873020c0.png)

I think this looks nicer (name and author to the side):
![Screenshot_20221014-222237_Firefox](https://user-images.githubusercontent.com/50382414/195937232-06fb4bc4-142b-4bf0-a11a-3c7f8a76c4e6.png)

**Comment by Donkey-Doug** [comment]
Also, when you scroll up the name is shown to the left in the top bar. I think it looks neat if it is already located to the left to make the transition more natural.

**Comment by Jordan-Dixon** [comment]
Some people for whatever reason do want the full package name, I suggest we put that either at the bottom or in the description.

**Comment by Iamlooker** [comment]
> Also, when you scroll down the name is shown to the left in the top bar. I think it looks neat if it is already located to the left to make the transition more natural.

That's a fair point, but the thing is if we align them to left this text will not look good with the bottom of the app info block.

But I have replaced the package name with author name and also made the app name bold
