### ISSUE TITLE
More useful info in header

### ISSUE THREAD

**Issue by Donkey-Doug** [Iamlooker/Droid-ify#127]
Currently the header looks like this:

![Screenshot_20221014-222119_Droid-ify](https://user-images.githubusercontent.com/50382414/195937773-5196070f-91fa-481f-96c4-607955804363.png)

It shows the version number, size and a link to the source code. I think it would be more useful to show:

- Date of latest release (to quickly see if the app is abandoned). I suggest to show "x days ago" and after 3 months just the date (mm-dd-yyyy).
- Size
- Antifeatures if it has some (just a quick overview, the user can scroll down to see all anti features. Just show a yes/no for anti features).

**Comment by magnus-ISU** [comment]
> Date of latest release (to quickly see if the app is abandoned). I suggest to show "x days ago" and after 3 months just the date (mm-dd-yyyy).

Implemented in #121 lol

**Comment by magnus-ISU** [comment]
Might be worth looking at #73

**Comment by Donkey-Doug** [comment]
@magnus-ISU I tried the debug version and like it. One tip: make the padding/margin around the install button symmetrical (same amount of space after as before):

![Screenshot_20221014-225132_Droid-ify-Debug](https://user-images.githubusercontent.com/50382414/195941957-8735a231-da96-4397-848d-0de423e3e3a0.png)

**Comment by magnus-ISU** [comment]
That was a problem I noticed too. But I'm not sure how to do it, it doesn't seem like there's padding above it. I wanted to just remove the padding above rather than add some below but I might do that instead.
