### ISSUE TITLE
Why is Droid-ify open source if you will not accept PRs?

### ISSUE THREAD

**Issue by githubaccountofme** [Iamlooker/Droid-ify#128]
> Don't Edit Source Strings or Send Pull Request

**Comment by Iamlooker** [comment]
Did you ever sent a PR
I meant dont change source strings and if you "have to" then send pr

**Comment by Iamlooker** [comment]
Will fix the grammer.
But just to let you know this grammer is also correct

**Comment by machiav3lli** [comment]
I thunk this can be misread, maybe "If you'd like to edit source string then you can gladly make a PR, just avoid using Weblate for it" would a better fotm
