### ISSUE TITLE
Merge donate and links

### ISSUE THREAD

**Issue by Donkey-Doug** [Iamlooker/Droid-ify#133]
Technically the donate section is a link to a payment service. The main interface issue is that multiple links may be available for donations.

![Screenshot_20221015-002551_Droid-ify-Debug](https://user-images.githubusercontent.com/50382414/195952714-240c9f59-221e-4f5b-a2e3-2f8f524399d0.png)

**Comment by Iamlooker** [comment]
Naah, `Donate` sections is a direct direction for those links. Putting them under a already blasted section would be bad UX
