### ISSUE TITLE
"Downloaded foo, tap to install" notification remains after installation

### ISSUE THREAD

**Issue by haarp** [Iamlooker/Droid-ify#134]
Using version 0.4.1 from the official F-Droid repo and normal install mode. When installing an app via the Install button, it is downloaded and installed just fine. However, after installation, a "Downloaded appname, Tap to install." notification remains. Same after updates.

This didn't occur in Foxydroid. It removed the notification after installation was completed.

Thanks!

**Comment by Iamlooker** [comment]
Fixed already.

Wait for next Release (Spoilers: Long Time)

**Comment by maximbaz** [comment]
The latest version changes the notification from "Downloaded" to "Installed", do we really need those notifications in case of success? Just wondering, why not remove them, as it was done in Foxy-droid?
