### ISSUE TITLE
Remove "Details" shortcut

### ISSUE THREAD

**Issue by Donkey-Doug** [Iamlooker/Droid-ify#134]
Pressing the details shortcut opens android settings. I do not think this function is needed. I also do not know of any other store (play, apple app store, ms store) that has such a shortcut.

![Screenshot_20221015-003036_Droid-ify-Debug](https://user-images.githubusercontent.com/50382414/195953243-4ca42f47-717e-4932-ad47-ddc9baea07ae.png)

**Comment by uli-on** [comment]
I'm absolutely neutral re this issue, but I'm totally averse re the argument "no other app has this". What's the reason for having different apps at all if they do not differ in any point of their outworking?

**Comment by Donkey-Doug** [comment]
So you are telling me you used this functionality only once and you still think it is good to keep it?

Also, on Android you could just go to settings > apps and the 4 most recent apps (and before android 12, 3 most recent apps) are shown immediately.

**Comment by Iamlooker** [comment]
Ya but just because it is not "very" useful doesn't mean we should remove it. I totally disagree with this method of Minimalism.

I don't think it is very useless I know many users who use it very very frequently.

**Comment by magnus-ISU** [comment]
To further support keeping it; if you don't use the feature, and it gets removed, you don't benefit as your toolbar just has a bit of extra whitespace. If you do use it you will be sad.

**Comment by Donkey-Doug** [comment]
The consensus seems clear. Feel free to close this issue. I still think it is not needed and provides visual clutter, but I am the minority.

**Comment by Donkey-Doug** [comment]
User: Maybe we should remove "Details"

Dev: Makes "Details" the largest button in the entire app.


Memes aside, I personally miss the launch button. If you wish to keep the details button, feel free to keep it.

**Comment by Iamlooker** [comment]
> User: Maybe we should remove "Details"
> 
> Dev: Makes "Details" the largest button in the entire app.
> 
> Memes aside, I personally miss the launch button. If you wish to keep the details button, feel free to keep it.

Launch button is still there, Details will be shown when the app can either not be launched or is already in foreground.
Try installing any app and opening the page.

**Comment by Donkey-Doug** [comment]
My bad, you are correct.
