### ISSUE TITLE
Rename Available to Explore

### ISSUE THREAD

**Issue by Donkey-Doug** [Iamlooker/Droid-ify#135]
There are three tabs: Available, Installed and Updates. I think Explore makes more sense than Available.

**Comment by magnus-ISU** [comment]
Furthermore, is there any point to having `Installed` and `Updates` be different? `Updates` has a horizontal and vertical view that both do the same thing - the horizontal updates view should just be shown at the top of `Installed` and `Updates` should be removed.

This should be a different issue though

**Comment by Donkey-Doug** [comment]
> ~Furthermore, is there any point to having `Installed` and `Updates` be different? `Updates` has a horizontal and vertical view that both do the same thing - the horizontal updates view should just be shown at the top of `Installed` and `Updates` should be removed.~
> 
> ~This should be a different issue though~
> 
> oh no that's how neo store works. Which is how droid-ify should work

I like the dedicated updates tab. I can sort on recently updated or newly added if I want. No need for a new tab or section in my opinion.
