### ISSUE TITLE
Bottom navigation

### ISSUE THREAD

**Issue by Donkey-Doug** [Iamlooker/Droid-ify#137]
Currently there are three tabs; Explore, Installed and Updates. I believe these could be moved to a bottom bar. One important thing to mention now: if the move to a bottom bar happens, please think about how to hide it on scroll. Most devs have trouble adding hide on scroll to existing elements.

As an example of an app with nice material you design and a bottom bar, see libretube: https://github.com/libre-tube/LibreTube

**Comment by magnus-ISU** [comment]
I don't think there's a need - you can swipe from side to side to change tabs already

**Comment by Iamlooker** [comment]
Yes this is planned once I am done migrating to `Navigation Components`

**Comment by vertigo220** [comment]
Personally, I prefer it at the top and labels vs icons. and having both, as in the example given, results in a large nav bar. If anything, I'd say keep the labels/tabs at top and move the search, filter, etc to the bottom.

**Comment by Iamlooker** [comment]
Same as #10
