### ISSUE TITLE
[Feature Request] Shizuku Service to Install Apps

### ISSUE THREAD

**Issue by PandoraHayami** [Iamlooker/Droid-ify#14]
Shizuku is a tool to use higher privileges (Mainly, ADB level privileges) on non-root devices, you do not need root for this. It could be an option to install applications and install updates in the background like with the root installer.

**Comment by Iamlooker** [comment]
This is a hard one but I will try to acheive this before 0.5.x

**Comment by Iamlooker** [comment]
Added 😉
