### ISSUE TITLE
Crash when doing updates

### ISSUE THREAD

**Issue by M4TH1EU** [Iamlooker/Droid-ify#140]
I was updating one by one my apps and suddenly the app crashed, tried again and it crashed again, I wasn't able to reproduce a third time though.

Here is the crash log : https://bin.kv2.dev/~61b452c4410e7c32e6696e3e

**Comment by Iamlooker** [comment]
This has been fixed already but wait for next update before closing

**Comment by Iamlooker** [comment]
5f64a8f07123eb7bcb96358d660e047013a3ba2b

Fixed Here will be available in next update
