### ISSUE TITLE
Missing translation of "Show less"

### ISSUE THREAD

**Issue by ygz213** [Iamlooker/Droid-ify#141]
**Version:** builded apk from source code (today)

Weblate says Turkish translation is 100% but:
![a](https://user-images.githubusercontent.com/77006222/145681450-4ba28b5e-68fe-4488-8bfa-9348de2a2816.png)

This is same in other languages:
![b](https://user-images.githubusercontent.com/77006222/145681453-8e2a0be7-8e3e-4b90-88a6-bcbbfc583484.png)

**Comment by ygz213** [comment]
my "show less" translation suggestion is "Daha az göster"

**Comment by Iamlooker** [comment]
Noted
