### ISSUE TITLE
Remove header background

### ISSUE THREAD

**Issue by Donkey-Doug** [Iamlooker/Droid-ify#141]
This is what the header looks like right now:

![Screenshot_20221018-010557_Droid-ify-Debug](https://user-images.githubusercontent.com/50382414/196299936-9005d259-28cc-4fe1-b3f4-642a8fd08116.png)

Compare this with for example the play store:

![Screenshot_20221018-010815_Aves](https://user-images.githubusercontent.com/50382414/196300012-7b3c0844-5cc9-4358-a19e-799c41ffdc7b.png)

Note that this also solves #124

**Comment by Jordan-Dixon** [comment]
It's a button, it needs the background in order to show that it is indeed a button.

**Comment by Jordan-Dixon** [comment]
For example, the install button, if you remove the background then it's harder to know it is a button or press-able.

**Comment by Iamlooker** [comment]
> It's a button, it needs the background in order to show that it is indeed a button.

True

And sorry I wont be removing the header background. I am not saying that Play Stores UI is bad but I personally this ours UI is not bad as well
