### ISSUE TITLE
Author name

### ISSUE THREAD

**Issue by Donkey-Doug** [Iamlooker/Droid-ify#143]
Currently the author name has some other info. For example, the author of VLC is videolan, but droidify says org.videolan.vlc. Is it possible to only show videolan? ~I looked at many apps and the author name seems to be always the first word after the first . (dot).~

![Screenshot_20221018-011825_Droid-ify-Debug](https://user-images.githubusercontent.com/50382414/196301214-9480c17f-2ad1-47ca-a582-7cb3effe0527.png)

**Comment by magnus-ISU** [comment]
That is not the author name but the package id. It is used as a unique identifier for the app by Android itself.

I would probably agree that showing that is not very useful, and that the author should be shown instead.

Maybe the app id can be moved down to the versions section, like `Versions of org.videolan.vlc` or something?

**Comment by uli-on** [comment]
Cause that string's field is searchable, it can be used to look up installations that left their traces in file directories but weren't removed by the deinstallation process. The mere author name - though better looking - would help in considerably less cases.
