### ISSUE TITLE
Diffrentiate sorting order for Available and Installed categories

### ISSUE THREAD

**Issue by dhishkyaon** [Iamlooker/Droid-ify#146]
Right now the sorting order for both Available and Installed categories is same. Instead it should work separatly. 

For example i prefer Available sorted by Recently Updated and Installed by Alphabetical order which is the default behaviour for many App Stores.

**Comment by dhishkyaon** [comment]
+ some UI fixes suggestions if you don't mind 😁

![PicsArt_12-15-10.03.45.jpg](https://user-images.githubusercontent.com/88529066/146226470-400ad277-ebde-422a-abf5-34a297c711dc.jpg)

**Comment by machiav3lli** [comment]
Actually there'll be a more comprehensive design change, so this is obsolete. You may follow the discussion on #117.
