### ISSUE TITLE
Collapse "Versions" section by default

### ISSUE THREAD

**Issue by Donkey-Doug** [Iamlooker/Droid-ify#147]
I think the versions section should be collapsed by default. Perhaps also rename it to "version history" or "older versions"

**Comment by uli-on** [comment]
Apart from having visual homogenity, what's the advantage of having it collapsed by default? Are there sections deeper down the page that you can access easier? 

I don't want to oppose right off, hence my questions, but the versions section is the region I almost always refer to, and it would drive me crazy if I'd have to tap on one of these mini knobs each time before I can see how many versions back mine is, how often the app gets updated, when the last update was, how apk sizes compare.

**Comment by Donkey-Doug** [comment]
On Android 12 apps can be updated in the background by third party app stores. I don't think keeping a close eye on versions is needed anymore. Also, there is a pull request to show the date of the latest release in the header. 

It also makes droidify look "complicated" and I think it might be better for mainstream adoption to not show lots of info they do not need.

**Comment by Donkey-Doug** [comment]
> if I'd have to tap on one of these mini knobs each time

You can tap anywhere. See highlighted area:

![Screenshot_20221021-013457_Droid-ify](https://user-images.githubusercontent.com/50382414/197078551-10f43fe5-d056-4e38-b2b7-37d32188c62b.png)

**Comment by magnus-ISU** [comment]
Disagree. There is nothing below to scroll to. All it does is make it somehow feel 'sleeker' but also less easy to do certain things, and no easier to do anything else.

That said,

> On Android 12 apps can be updated in the background by third party app stores. 

I don't think Droid-ify implements this – *that* is a much more worthwhile thing to work on

**Comment by Donkey-Doug** [comment]
> I don't think Droid-ify implements this – that is a much more worthwhile thing to work on

It is partially implemented. I am on android 12 and I need to manually download updates. However, once downloaded they auto install without user intervention.
