### ISSUE TITLE
Merge install button and versions overview

### ISSUE THREAD

**Issue by Donkey-Doug** [Iamlooker/Droid-ify#147]
I suggest merging the install button and versions view by using a split button.

Examples:
![split-buttons](https://user-images.githubusercontent.com/50382414/146248143-71f2d530-fe69-42c0-842e-703914fb353f.png)

One could press the button to instantly install the recommended version, or press on the dropdown arrow to reveal other versions.

More examples:
![Microsoft-store-install-button-greyed-out](https://user-images.githubusercontent.com/50382414/146298214-a60e4ca6-491c-4a7a-92c5-7b04de077f39.jpg)

**Comment by machiav3lli** [comment]
Nope, this is an UX nightmare!

**Comment by Donkey-Doug** [comment]
> Nope, this is an UX nightmare!

Ah, I thaught it was a really good method of cleaning up the UI.

**Comment by machiav3lli** [comment]
@NoahAndrews exactly. Plus cleaner isn't per se more accessible, sometimes even less.
