### ISSUE TITLE
Remove unnecessary info from versions section

### ISSUE THREAD

**Issue by Donkey-Doug** [Iamlooker/Droid-ify#148]
![Screenshot_20221021-013022_Droid-ify](https://user-images.githubusercontent.com/50382414/197078631-2ff38470-7f7b-49ad-bd95-df672f701053.png)

Some releases have a signature (I think it is the releases from the fdroid repo). Is this info useful to people? If not, perhaps we could remove it.

Also, I think that we do not need to write "VERSION 0.1.2" for every release. v0.1.2 should be enough.

**Comment by GameOverFlowChart** [comment]
It is helpful because you can't update from a version with a different signature to another without uninstalling and losing data. A better question would be, is it important enough. Maybe for most people it's not important but than again why are we showing outdated versions, most people would only be interested in the installed version, the newest version per repo and the newest stable version per repo.

**Comment by GameOverFlowChart** [comment]
That's my point. There are times signatures are useful just like old versions. The difference is that signatures take much less place. So if you want to remove something to make room, old versions make more sense. But I don't think we need to remove anything. On the other end, the idea to only show different signatures isn't even that bad. You wouldn't even need to show the signature itself but just a "signature mismatch" warning or something. But again, I don't think we need to remove them at all.

**Comment by Iamlooker** [comment]
> That's my point. There are times signatures are useful just like old versions. The difference is that signatures take much less place. So if you want to remove something to make room, old versions make more sense. But I don't think we need to remove anything. On the other end, the idea to only show different signatures isn't even that bad. You wouldn't even need to show the signature itself but just a "signature mismatch" warning or something. But again, I don't think we need to remove them at all.

Yes I totally agree, minimalism is only good till it starts bothering with user experience. I will be closing this issue, as removing signature from the release item doesn't actually achieve any relatively large goal.
