### ISSUE TITLE
[BUG] App versions multiplying

### ISSUE THREAD

**Issue by Wojtaz0w** [Iamlooker/Droid-ify#15]
**I'm sorry for any mistakes, English isn't my primary language**
I've noticed the bug on Mull and F-Droid.
How to trigger bug:
1. After going to F-Droid **(obviously in Droid-ify)** and scrolling down to versions you'll see 1.15.2, 1.15.1, 1.15, 1.15-alpha1, 1.15-alpha0. **(SCREENSHOT1)** 
2. After clicking **show older versions** versions 1.14, 1.14-alpha5 and 1.14-alpha3 will appear. **(SCREENSHOT2)** 
3. Next click show less - that will cause 1.14-alpha3 to be hidden. You'll still see 1.14 and 1.14-alpha5 **(SCREENSHOT3)** 
4. button name won't change, and clicking it again will cause 1.14, 1.14-alpha5 and 1.14-alpha3 to be multiplied - you can just keep pressing show less button. **(SCREENSHOT4)** 
DROID-IFY VERSION: 0.4.5

Screenshot 1
![1 Ss_bug_droidify](https://user-images.githubusercontent.com/104674625/177646913-4fa34a79-9fbd-4ea1-b561-b60424619908.png)

Screenshot 2
![2 Ss_bug_droidify](https://user-images.githubusercontent.com/104674625/177646920-07ad2b9d-fcdb-4406-86b4-3b5a17f447db.png)

Screenshot 3
![3 Ss_bug_droidify](https://user-images.githubusercontent.com/104674625/177646926-a2aae16a-4a7d-4e70-9db9-a91df405b1c6.png)

Screenshot 4
![4 Ss_bug_droidify](https://user-images.githubusercontent.com/104674625/177646930-a8696413-705e-4ba3-934a-308f675ab8df.png)

**Comment by Iamlooker** [comment]
Ooh ya this will be fixed in next release 😊
