### ISSUE TITLE
Auto download updates

### ISSUE THREAD

**Issue by Donkey-Doug** [Iamlooker/Droid-ify#150]
I am on android 12 and app updates are installed automatically (without a popup asking me if I want to install).

However, I still need to download each update myself. If droid-ify can auto download updates, then my apps will always be up to date without user interaction. Neo-store already has this. Perhaps look at its code.

Also, please have an option in settings) to show a notification every time an app is updated in the background. Make it possible that the notification directly links to the changelog in github/gitlab.

**Comment by BlitDev** [comment]
I'm also on Android 12 (crDroid), so I'm in favor.

**Comment by Iamlooker** [comment]
Merge with #120 please

**Comment by Iamlooker** [comment]
> I am on android 12 and app updates are installed automatically (without a popup asking me if I want to install).
> 
> However, I still need to download each update myself. If droid-ify can auto download updates, then my apps will always be up to date without user interaction. Neo-store already has this. Perhaps look at its code.
> 
> Also, please have an option in settings) to show a notification every time an app is updated in the background. Make it possible that the notification directly links to the changelog in github/gitlab.

Droid-ify supports and utilizes every PackageInstaller API, the thing is the `Silent Update` is a bit confusing. You can read [this ](https://developer.android.com/reference/android/content/pm/PackageInstaller.SessionParams#setRequireUserAction(int))to under stand this more
