### ISSUE TITLE
[BUG] Screenshot not showing

### ISSUE THREAD

**Issue by mogh-k** [Iamlooker/Droid-ify#150]
Whenever I tap on a screenshot preview, the one I first tapped doesn't appear. The rest of the screenshots do show up, though. A video below shows this:
https://user-images.githubusercontent.com/85471481/146657263-f7f90120-267e-49f5-93c6-41cbac5a212f.mp4
It's really only a problem when there is only one screenshot and I can't look at any others.

**Comment by machiav3lli** [comment]
Duplicate to #104 and other closed issues
