### ISSUE TITLE
Auto-updating apps after updating repos

### ISSUE THREAD

**Issue by soredake** [Iamlooker/Droid-ify#152]
Would be nice to have such option.

**Comment by yephny** [comment]
Duplicate of #3

**Comment by soredake** [comment]
By updating i mean upgrading, instaling updates

**Comment by yephny** [comment]
Oh, I thought they were trying to say auto installing updates in #3 but all that's been mentioned is auto downloading, you might be onto something.

**Comment by machiav3lli** [comment]
Already solved in #159
