### ISSUE TITLE
Limit an app to only track one repo/ignore other repos

### ISSUE THREAD

**Issue by jeremiah-miller** [Iamlooker/Droid-ify#154]
**Is your feature request related to a problem? Please describe.**
An app I have installed (https://apt.izzysoft.de/fdroid/repo/org.btcmap_35.apk, https://github.com/teambtcmap/btcmap-android) is constantly releasing ever couple days on izzyondroid, but the app is also on the normal fdroid repos and doesn't have such frequent updates. It's annoying constantly having this app listed in the updates section

**Describe the solution you'd like**
I'd like to be able to ignore izzyondroid updates for this app, and more generally be able to limit certain apps to certain repos

**Describe alternatives you've considered**
Could also ignore updates for certain apps, or have auto updates for certain apps so i don't ever notice it

**Comment by Iamlooker** [comment]
You cannot update apps from two different repos, I am assuming one of them signs the app themself and the other one is the author signed apk. But I will see what I can do to resolve this issue

**Comment by jeremiah-miller** [comment]
I'm pretty sure i'm able to switch between repos when choosing updates, but i'll try uninstalling the app and installing the fdroid version

**Comment by jeremiah-miller** [comment]
Oh yeah, installing it via fdroid causes it to not show updates from izzy. I think this ticket is safe to close, thanks!

**Comment by Iamlooker** [comment]
Good to hear :)
