### ISSUE TITLE
[Bug] Share button in the top right of application pages sometimes doesnt appear

### ISSUE THREAD

**Issue by Username58260** [Iamlooker/Droid-ify#155]
When you open a application page the share button is very inconsisent on when it appears (on one device it doesnt appear at all, on another it only appears for installed applications)

![FileName__0](https://user-images.githubusercontent.com/95015583/147525261-1f4ee6d8-d625-4ce6-a138-f754a5e3b09c.jpg)

![FileName__1](https://user-images.githubusercontent.com/95015583/147525271-14c48b1d-0955-469c-b378-e53f41691a8f.jpg)

**Comment by Iamlooker** [comment]
Duplicate of #34
