### ISSUE TITLE
per-release changelogs missing

### ISSUE THREAD

**Issue by IzzySoft** [Iamlooker/Droid-ify#156]
since `versionCode: 43` there were no new changelogs added to the Fastlane structure. Just a lapsus, or intention? If no new changelogs are planned I'd simply disable them in my repo – but the more welcome result would be the new ones showing up again (re-starting with 50 is fine).

**Comment by Iamlooker** [comment]
Ooh shit I havent pushed the commit yet on GitHub, my bad

**Comment by Iamlooker** [comment]
I will not make this mistake from next release. 😥

**Comment by Iamlooker** [comment]
This jas been added iin 51, aorry for inconvenience

**Comment by IzzySoft** [comment]
Pah. Failed again.
Branch was renamed from `master` to `main`.
Before I start yelling,
Remember me telling :zany_face: :dash:
