### ISSUE TITLE
Missbehaving button to show more/less versions

### ISSUE THREAD

**Issue by Donkey-Doug** [Iamlooker/Droid-ify#157]
Since update 0.5.1 (but I skipped 0.5.0) the button to show more versions missbehaves. The functionality is fine, but the text is wrong.

Sometimes it says "show older versions" and sometimes it says "show more". When expanded, the text sometimes still says "show older versions" or "show more" and sometimes it says "show less". However, after collapsing again the text "show less" is then still shown.

**Comment by Iamlooker** [comment]
I cannot reproduce this issue, but I will go through the code again

**Comment by Iamlooker** [comment]
I still cannot reproduce this bug and nor am I able to find an issue in the bug

**Comment by Donkey-Doug** [comment]
Here I recorded two cases. Both cases behave differently.


https://user-images.githubusercontent.com/50382414/203403957-f2450186-9c50-4ffc-93d9-c40351e9b91f.mp4


https://user-images.githubusercontent.com/50382414/203403996-e2fac633-fe55-4507-859f-aa8d3d71205b.mp4

**Comment by vertigo220** [comment]
Just tested this with the examples given and the button says "SHOW OLDER VERSIONS" constantly as mentioned. I tap it, it shows an additional version, but the button still has the same text. I tap it again, it collapses to hide that version, and the button text stays the same. I was on 0.4.9 of Droid-ify when I first repro'd this, then updated to 0.5.1 and it was still doing it.
