### ISSUE TITLE
[BUG]: "Error Installing Droid-ify"

### ISSUE THREAD

**Issue by RetroAbstract** [Iamlooker/Droid-ify#158]
When trying to update from 4.9.0 to 5.0.0 or 5.0.1, I'm met with "Error Installing Droid-ify - Failed to install due to an unknown error".

Tried installing 5.0.0 & 5.0.1 through F-Droid & directly by downloading the apks from Releases here but same result.

OS: Lineage OS Android 11, latest build (23/10/2022)

**Comment by foss-** [comment]
You will have to remove and re-install as per 0.5.0 release notes https://github.com/Iamlooker/Droid-ify/releases/tag/v0.5.0

**Comment by RetroAbstract** [comment]
> You will have to remove and re-install as per 0.5.0 release notes https://github.com/Iamlooker/Droid-ify/releases/tag/v0.5.0 Seems something with signing keys got messed up. Was unable to find details as to what happened.

I did also remove Droid-ify 4.0.9 both directly through Lineage and through F-Droid before trying to install 5.0.0 & 5.0.1 but I still got & get "Error Installing Droid-ify - Failed to install due to an unknown error".
