### ISSUE TITLE
The checkbox to ignore updates is too easy to press accidentally while scrolling

### ISSUE THREAD

**Issue by opk12** [Iamlooker/Droid-ify#159]
The checkbox to ignore updates is too easy to press accidentally while scrolling.

**Comment by Iamlooker** [comment]
Where else can we place those buttons?

**Comment by Donkey-Doug** [comment]
See https://github.com/Iamlooker/Droid-ify/issues/118 and https://github.com/Iamlooker/Droid-ify/pull/122

**Comment by Donkey-Doug** [comment]
There are many non-merged pull requests by the way.

**Comment by Iamlooker** [comment]
> There are many non-merged pull requests by the way.

He personally told me some of them are mergable, but I think there are some points of conflict between my ideas and his. I will try to sort this, but he seems to be a bit busy for now. And I will get busy as well in few days.

**Comment by Iamlooker** [comment]
Merge with #118
