### ISSUE TITLE
Copy app id

### ISSUE THREAD

**Issue by opk12** [Iamlooker/Droid-ify#160]
Open the page for an app, the id is below the name. It would be nice to be able to copy the app id with a long-tap.

**Comment by uli-on** [comment]
One upward thumb by me. Like I wrote in #143
> Cause that string's field is searchable, it can be used to look up installations that left their traces in file directories but weren't removed by the deinstallation process.

Or for searching elsewhere like in Netguard. (Sorry for the duplicate, can't copy links to posts here in Octodroid)

**Comment by opk12** [comment]
Or for searching a crash in the logcat to report upstream.

**Comment by opk12** [comment]
@Iamlooker This is not fixed yet. The app id appears, but I can't copy it. I tried to do a short tap and a long tap. Should I open a new issue?

**Comment by Iamlooker** [comment]
I will fix this in next release
