### ISSUE TITLE
[Weblate] Unable to start new translation

### ISSUE THREAD

**Issue by Generator** [Iamlooker/Droid-ify#161]
## Description
When trying to start a new translation "Portuguese (Portugal)" always get logout with the message:   
> Your request was rejected because you have performed too many operations recently. You have been signed out, please sign in and try again later.

Possible related WeblateOrg/weblate#5802

**Comment by Iamlooker** [comment]
I have added Portuguese (Portugal) for now and will look into this isse

**Comment by Iamlooker** [comment]
Can anyone else confirm this issue?

**Comment by Iamlooker** [comment]
Seems like other users are also able to add languages
