### ISSUE TITLE
Droid-ify doesn't list itself in the updates tab

### ISSUE THREAD

**Issue by uli-on** [Iamlooker/Droid-ify#162]
I've version 0.4.9 installed from the Izzy repo and none of the the newer versions have been proposed as updatable. I had expected that for versions from the F-Droid repo but not for the same than I installed it from.

As a result I have the android info button (not the Start button) where the Update button should be. In the version info section I get the recommended badge for v0.5.1, though.

**Comment by Iamlooker** [comment]
Sorry but there is no way for me to fix this. I am sorry for the inconveniences
