### ISSUE TITLE
App icon is not shown for many apps

### ISSUE THREAD

**Issue by opk12** [Iamlooker/Droid-ify#164]
The app icon is not shown for many apps, for example Fennec (`org.mozilla.fennec_fdroid`), NextPush (`org.unifiedpush.distributor.nextpush`), Kodi (`org.xbmc.kodi`).

For some apps, this is also the description and/or changelog, so I opened a separate issue #165 for that.

**Comment by Iamlooker** [comment]
This issue seems to be with fdroid repository Droid-ify can't do anything bout it

**Comment by Iamlooker** [comment]
This issue is related the the targeted apps not with FDroid or Droid-ify. See tl[this](https://gitlab.com/fdroid/fdro)

**Comment by opk12** [comment]
Can you fix the link? It is broken

**Comment by Iamlooker** [comment]
> Can you fix the link? It is broken

Link is updated
