### ISSUE TITLE
Privacy Policy

### ISSUE THREAD

**Issue by johndoe432** [Iamlooker/Droid-ify#164]
Does Droid-ify collect any personal information? If it does, for how long is it stored?

**Comment by Iamlooker** [comment]
We dont collect any sort of data.

All the data is stored on your device which is generally the cache of the icon and apks which you downloaded.

They are stored at `data/data/com.looker.droidify/`

**Comment by johndoe432** [comment]
> We dont collect any sort of data.
> 
> All the data is stored on your device which is generally the cache of the icon and apks which you downloaded.
> 
> They are stored at `data/data/com.looker.droidify/`

I understand. Thanks for your answer 😄
