### ISSUE TITLE
Icon, description, changelog are not shown for org.billthefarmer.notes

### ISSUE THREAD

**Issue by opk12** [Iamlooker/Droid-ify#165]
Icon, description and changelog are not shown for many apps, for example [this one](https://f-droid.org/en/packages/org.billthefarmer.notes/).

As the changelog is volatile, I'll copy the current one here, for version 1.31: `New in version 1.31 * Add superscript and subscript`

For many apps, the problem is only the icon, so I opened a spearate issue #164 for that.

**Comment by Iamlooker** [comment]
This is not an issue with Droidify, the above mentioned app doesn't have its metadata listed for FDroid

**Comment by opk12** [comment]
What do you mean exactly? The info appear in the F-droid app (screenshot below) and on the website ([link](https://f-droid.org/en/packages/org.billthefarmer.notes/)), so the metadata must be there?

![b](https://user-images.githubusercontent.com/40740650/201078016-452bb67b-6c66-4778-ba7a-48c5263663d5.png)
