### ISSUE TITLE
sha?

### ISSUE THREAD

**Issue by yetimind** [Iamlooker/Droid-ify#17]
I'd like to verify the Droid-ify .apk package downloaded from github before running it locally but cannot find your shasum. If it is on github or extenally, could you point me to it? Otherwise, if not signed, how to verify?

**Comment by Iamlooker** [comment]
SHA will be available in future updates

**Comment by mhmdanas** [comment]
@yetimind checksums are not intended to verify the authenticity of data, only its integrity. In other words, checksums only allow you to check that the data wasn't corrupted in transmission, not that the data is actually coming from its authentic source. For instance, if a malicious actor were to publish an APK with malware in it, they will only need to generate the checksum of that APK.

**Comment by Iamlooker** [comment]
It is available in new release
