### ISSUE TITLE
Weird things in this latest version

### ISSUE THREAD

**Issue by gallegonovato** [Iamlooker/Droid-ify#170]
Good afternoon:

In this latest version I am noticing strange things. That the application did not do before. 

For example I'm seeing that premium fdroid things. For example an application (that I do not know because I have installed from github) lte cleaner. I only see the fdroid repository. Even having fdroid and Izzy. 

Instead Magisk that if I install from github. I only get the Izzy sources

And for example the applications that are already installed allows me to redownload and install them.

Note that also happens the same on other phones. My sister in law uses things from github and only suggests and appears things from fdroid.

For example she has Simple Flashlight version 5.8.2 from github installed and in the app it marks 5.8.2 from fdroid as suggested. And the same thing happens with Newpipe, and many more. 

On the other hand with Droid-ify if it leaves the two repos. And Izzy's as installed.

I upload screenshots:

https://ibb.co/5LTZgDF
https://ibb.co/7JYfY69
https://ibb.co/hLwzFw2
https://ibb.co/NmYGfkJ
https://ibb.co/XYDGvBY

A hug

**Comment by gallegonovato** [comment]
Good afternoon @Iamlooker

Thanks for all your work and help :)

I'll pass you an option that several people who use your application tell me about. We had already discussed it but they insist me to ask you. Since they don't have an account in github.

They tell me if you can add to the duration of the cleaning. An option that is never. That is to say that this cleaning is not carried out if the user does not want.

They tell me that it is to give more freedom to the user and so that the application does not run alone. Since they tell me that after charging the mobile (turned off the mobile), when they start it this runs.

Some tell me that they looked at sd maid for example.

What I pray, do not kill the messenger. Since I only transmit what they tell me.

Thank you very much for your help and time.

**Comment by gallegonovato** [comment]
Good afternoon:

Today when updating the source lists Flashlight Tiramisu came out but it comes out with nothing to download. 

I don't know if it's fdroid's or izzy's failure to catch the file.

It's in fdroid https://f-droid.org/packages/com.pdb82.flashlighttiramisu/ and https://github.com/polodarb/Flashlight-Tiramisu

A hug and sorry for giving you the tabarra so much.

**Comment by Iamlooker** [comment]
> In this latest version I am noticing strange things. That the application did not do before. 
> 
> For example I'm seeing that premium fdroid things. For example an application (that I do not know because I have installed from github) lte cleaner. I only see the fdroid repository. Even having fdroid and Izzy. 
> 
> Instead Magisk that if I install from github. I only get the Izzy sources
> 
> And for example the applications that are already installed allows me to redownload and install them.

LTE Cleaner is only visible on FDroid because  the dev decided to remove the app from Izzy4Droid. Izzy gives you an option after adding the app to FDroid, wether we want the app on both repo or only FDroid.

And Magisk is not available on FDroid afaik. It is only available on Izzy4Droid.

Thanks for using the app. :)

**Comment by Iamlooker** [comment]
> They tell me if you can add to the duration of the cleaning. An option that is never. That is to say that this cleaning is not carried out if the user does not want.

This would actually cause some issues. As the app can start growing in size really quickly. I mean really quickly. It can also cause crashes if the obselete files are not deleted as we might start reading from seperate file. Maybe we can allow infinite duration for only apk file. I will look into this.

> They tell me that it is to give more freedom to the user and so that the application does not run alone.

Ya surely it would. I will look into this topic.

> What I pray, do not kill the messenger. Since I only transmit what they tell me.

🔫🔫 Bam

**Comment by Iamlooker** [comment]
> Today when updating the source lists Flashlight Tiramisu came out but it comes out with nothing to download. 

Ooh ya I have been aeeing similar issues on different devices. Can you please create a new issue named, `Show clear reason of incompatibbility`. I will add it to the 0.5.2 milestone.

**Comment by gallegonovato** [comment]
Good afternoon:

Not that it shoots me... ah... I've been hit. As an old ad in Spain used to say: Sorry to leave this world without tasting the pipes hahaha.

The truth that now with the various changes that google is doing in the Android. That even influence for lineageos, are giving many headaches.

And sometimes we do not realize all the work you developers have to make everything go well.

It's like yesterday that came out to me in the application to update the new version of Music, which brings by default the Lineageos I have on the phone. But of course the signature is different and it is a system application.

Thank you very much for all your time. And especially with the patience you have to solve the problems and with me ;)

Receive a warm hug

**Comment by Iamlooker** [comment]
I will closing this issue as I consider this fixed.
