### ISSUE TITLE
Change repositories arrangement

### ISSUE THREAD

**Issue by dhishkyaon** [Iamlooker/Droid-ify#171]
1. Automatically shift the active repositories to the top most of the list.

2. Show description of inactive repos. Currently only active repos are showing it.

3. Change 'Repository' to 'Repo name.

Image regarding 2nd & 3rd point -

![IMG_20220126_202202.jpg](https://user-images.githubusercontent.com/88529066/151186478-48f1d9ae-cf64-404c-a50a-b7e8bb3cb50c.jpg)

**Comment by machiav3lli** [comment]
#1 would be nice. On way. Maybe tonight.
#2 I think it makes sense to not connect to the inactive repositories, as this is what a user would excpect and this would avoid "spammy" calls to the repos.
#3 is obsolete with the new design. But maybe will find another form for it.

**Comment by dhishkyaon** [comment]
oh. i didn't know that it pings ths repo. my bad.
excited about the new design ^_^
