### ISSUE TITLE
Header appearence

### ISSUE THREAD

**Issue by Devil63833638** [Iamlooker/Droid-ify#175]
You should fix header like this.
![Screenshot_2022-11-23-15-49-18-24_bf5286d428c97f865e4b51a5afbaefcd](https://user-images.githubusercontent.com/118893880/203522506-1cfffc08-3370-4bae-b945-b80473b75d8f.jpg)

**Comment by Iamlooker** [comment]
I am planning to add a switch to allow both, current and above shown, state

**Comment by Iamlooker** [comment]
This has been fixed and will be available.in next update
