### ISSUE TITLE
Incorrect hindi translations 

### ISSUE THREAD

**Issue by Midnight1938** [Iamlooker/Droid-ify#177]
![worst-instance](https://user-images.githubusercontent.com/58230351/203854829-b0f6b83b-ba78-493a-a0b0-7d4f4e97c25d.png)

Recently started seeing sub par translations with latin characters.

Unable to find instance of this on weblate instance.

**Comment by Iamlooker** [comment]
This is very weird. I will look into this and report back

**Comment by Iamlooker** [comment]
This seems like a library issue. I cannot reproduce this specific issue. But seems to be fixed here, maybe be because of you commit which seems to be revoked by someone else's commit.

**Comment by Midnight1938** [comment]
> This seems like a library issue. I cannot reproduce this specific issue. But seems to be fixed here...

Ive tried reinstalling the app, but the problem persists

**Comment by Iamlooker** [comment]
> Ive tried reinstalling the app, but the problem persists

Can you try installing the alpha version from the telegram group?

**Comment by Midnight1938** [comment]
> > Ive tried reinstalling the app, but the problem persists
> 
> Can you try installing the alpha version from the telegram group?

Works fine in alpha

**Comment by ShareASmile** [comment]
Yes, that was fixed on weblate when i saw this translation which was inadvertently messed up by some one without full knowledge of the language "hi" "Hindi"
