### ISSUE TITLE
Italian string

### ISSUE THREAD

**Issue by opk12** [Iamlooker/Droid-ify#179]
In the details page for an app, `Size` should become `Dimensione`, the standard Italian word to denote software size. `Taglia` refers specifically about clothing and so it is incorrect.

**Comment by Iamlooker** [comment]
I have updated the string. It will be available in next update. It is fixed here 102bfeebed592c00809c6a6e01abb2236c1b1bc6

You can help translate Italian from [here](https://hosted.weblate.org/projects/droidify/localization/it/). You can change the string over there and the changes would be available in next update.
