### ISSUE TITLE
[Question] Option to update all apps at once

### ISSUE THREAD

**Issue by beyond9thousand** [Iamlooker/Droid-ify#180]
Is this doable? Would be great instead of having to manually hit update for each app.

**Comment by Iamlooker** [comment]
This is actually doable and is in my priority, but currently the code-base is going through a revamp phase. I would prefer to finish that and then start working on this. But this will surely be available before v0.6.x

**Comment by beyond9thousand** [comment]
Sweet! Looking forward to it.
