### ISSUE TITLE
Unresponsive/crashing when switching between landscape/portrait 

### ISSUE THREAD

**Issue by cYDN48** [Iamlooker/Droid-ify#188]
Steps to reproduce:
1. Open an app that is able to go into landscape mode (but stay in portrait mode for now)
2. Open Droid-ify ("Available" Tab, if not already there; Crash does not occur in the other tabs)
3. Tap the magnifying glass icon at the top, which should make the search text field and your keyboard appear
4. Switch to the other app and switch into landscape mode
5. Switch back to Droid-ify, which now updates to landscape mode and becomes unresponsive and crashes

Using Version 0.4.3 (F-Droid) on Android 12

**Comment by machiav3lli** [comment]
Thanks. This is fortunately no more relevant, as we have another base now.
