### ISSUE TITLE
New icon

### ISSUE THREAD

**Issue by Donkey-Doug** [Iamlooker/Droid-ify#192]
Can we maybe get a new icon? Something more modern. Perhaps a shopping bag?

**Comment by machiav3lli** [comment]
In couple of days you'll be surprised.

**Comment by yephny** [comment]
@machiav3lli I see, I must have misunderstood what you meant by "in a couple of days". I will see if I can preview the channel without account, thank you for your quick response.

**Comment by machiav3lli** [comment]
@fusionneur nope, you can always create your own and build the app yourself or use a custom icon in the launcher

**Comment by machiav3lli** [comment]
@fusionneur The lower quality is related to IzzyOnDroid repo, it should be better as soon as you sync the official fdroid repo.
