### ISSUE TITLE
[Bug] Long app names are cut off

### ISSUE THREAD

**Issue by GameOverFlowChart** [Iamlooker/Droid-ify#192]
If App names are too long than they get cut off (and there is no way to read the rest). In the case of Tor Browser, this means that both the Stable and the Beta version seem like the same app.
![Screenshot_2022-12-09-00-28-47-32_bf5286d428c97f865e4b51a5afbaefcd](https://user-images.githubusercontent.com/109205200/206589077-66cc1cd5-f94c-4ae9-86a0-a939608f134d.jpg)
![Screenshot_2022-12-09-00-30-53-43_bf5286d428c97f865e4b51a5afbaefcd](https://user-images.githubusercontent.com/109205200/206589088-6e12528b-4455-4c37-8686-cdeb5805b6ae.jpg)

**Comment by vertigo220** [comment]
Auto-scrolling probably wouldn't be ideal, same with word-wrapping, but maybe long-pressing could show the full name in a pop-up. Interestingly, on mine it says "org.torproject.torbrowser" and "org.torproject.torbrowser_alpha" in place of "by The Tor Project" so I wonder why there's a difference there.

**Comment by GameOverFlowChart** [comment]
> Interestingly, on mine it says "org.torproject.torbrowser" and "org.torproject.torbrowser_alpha" in place of "by The Tor Project" so I wonder why there's a difference there.

The repo is Guardian Project and Droid-ify is on 0.5.1. Android is on version 12.

**Comment by vertigo220** [comment]
Yeah, now that I've updated Droid-ify mine says the same as yours. Guess they changed it recently.
