### ISSUE TITLE
[BUG] Notification/Status bar download animated arrow stays animated after downloads/installs are complete

### ISSUE THREAD

**Issue by vertigo220** [Iamlooker/Droid-ify#199]
**Describe the bug**
See title.

**To Reproduce**
1. Update apps
2. Arrow animates and stays animated

**Expected behavior**
Arrow should become static once complete, or even change to a different icon altogether to indicate completion.

**Smartphone (please complete the following information):**
 - Device: Samsung A71 5G
 - OS: Android 12
 - Version v0.5.1

**Comment by Iamlooker** [comment]
This has been fixed in latest alpha version which is released on the telegram group. You can either try it (It wont replace stable version) or you can wait for next stable release.
