### ISSUE TITLE
Different color for installed and suggested version

### ISSUE THREAD

**Issue by mahdi1234** [Iamlooker/Droid-ify#2]
With 0.2 go over to app versions, both suggested and installed have the same color. Would be great to distinguish between those e.g. have installed in green for dark mode.

![colors](https://user-images.githubusercontent.com/1097047/136097789-7df00965-f46c-4b85-a40d-fc7c4a577ec0.jpg)

**Comment by Iamlooker** [comment]
Same as #5 [Done](https://github.com/Iamlooker/Droid-ify/commit/5d4fb29f9ef9e9cee91ef583ed5de1d40eee947a)
