### ISSUE TITLE
"Install All/Update all" button

### ISSUE THREAD

**Issue by balporig** [Iamlooker/Droid-ify#20]
Add "Install All/Update all" button on the Updates tab that can download and install all available updates. On non root devices it can show install prompts for each app

**Comment by BluePixel4k** [comment]
That would be awesome! 
Also on Android 12 there is the feature where app can be installed silent (this install method is already implemented, but still buggy).

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
@BluePixel4k, is silent installation relevant?

**Comment by BluePixel4k** [comment]
@BEEDELLROKEJULIANLOCKHART Yes of course! 😃 Thereby you don't have to manually allow every update even without root.

**Comment by balporig** [comment]
For silent non-root installation for Android 11 and below can be implemented with [RikkaApps/Shizuku: Using system APIs directly with adb/root privileges from normal apps through a Java process started with app_process.](https://github.com/RikkaApps/Shizuku)

**Comment by CodeCubeNeo** [comment]
What about an update all button for non root devices (something like the neo store or aurora droid)

**Comment by Iamlooker** [comment]
> What about an update all button for non root devices (something like the neo store or aurora droid)

Yes it is planned.

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
Instead of a dedicated "Update all" button, checkboxes beside each entry would be more versatile, with a dedicated "Check all" box atop them. After all, this problem has been remediated many times, and what I describe is the best system known. It would allow me to update many applications easily, but not necessarily all unless I want that, because occasionally I want to update merely 15 of 20, for instance, because I am using the last 5.

**Comment by CodeCubeNeo** [comment]
Good thinking. I agree.

**Comment by Tealk** [comment]
+1

**Comment by Iamlooker** [comment]
Sorry this will be done in next update for sure

**Comment by rokejulianlockhart** [comment]
@Iamlooker, did you consider my implementation of it? I believe that it is probably able to support future functionality better than solely a button.

**Comment by TippyLion28** [comment]
Another way you could do it is have an update all button but then opt out of updates for some apps, the same way it works in aurora store. 

This would work out better for most people who want to keep all apps up to date except for a few critical ones which require more careful consideration before updating.

Either way it gets implemented, this will be awesome to have :)
