### ISSUE TITLE
[Feature Request] Nearby Share

### ISSUE THREAD

**Issue by barraIhsan** [Iamlooker/Droid-ify#205]
**Is your feature request related to a problem? Please describe.**
Allows you to share an app to a friend easily (maybe usefeul?). Also, the feature is existed on F-droid

**Describe the solution you'd like**
Add Nearby Share?

**Describe alternatives you've considered**

\-

**Comment by Iamlooker** [comment]
This is not planned yet, so I can't tell you when this will be implemented

**Comment by git-Hmmm** [comment]
According to me, there isn't any need for this as it will make the code more heavy, why not keep it simple and minimal?, you can use F-Droid nearby standalone app as suggested by @linux2good.

**Comment by Iamlooker** [comment]
I agree with @git-Hmmm and @linux2good. I will be closing this issue
