### ISSUE TITLE
Consistent naming in sorting options

### ISSUE THREAD

**Issue by Donkey-Doug** [Iamlooker/Droid-ify#212]
**Is your feature request related to a problem? Please describe.**
Inconsistency annoys me.

**Describe the solution you'd like**
Rename What's New to New in sorting options and use similar capitalization. Currently the W and N in What's New are capitals, but the u in Recently updated is a lower case letter.

**Describe alternatives you've considered**

-

**Additional context**
![Screenshot_20230120-010022_Droid-ify](https://user-images.githubusercontent.com/50382414/213588803-274f16f8-7fd6-4972-a699-d20a5fded805.png)

**Comment by Iamlooker** [comment]
It is seems fine to me and I don't think any change is required
