### ISSUE TITLE
[BUG] Android 9: Droid-ify 0.5.1 is not recognized by certain apps

### ISSUE THREAD

**Issue by its-thomas** [Iamlooker/Droid-ify#216]
**Bug description**
While on my Android 10 phone, Droid-ify 0.5.1 (from F-Droid) works fine, on my Android 9 device, certain apps are having problems recognizing Droid-ify 0.5.1:

- Latest [KISS Launcher](https://github.com/Neamar/KISS) v.3.19.0 from F-Droid cannot find Droid-ify at all (meaning: never), neither via Search function, nor is it listed in its configuration (where all installed apps are listed), while the simple [Text launcher](https://f-droid.org/en/packages/ademar.textlauncher/) has no problems finding it.

- [Super Freeze](https://superfreezz.gitlab.io/) v.0.16.1 from F-Droid has similar problems, but not all the time: It generally lists all installed apps but often cannot find Droid-ify 0.5.1

- Same with [Netguard](https://netguard.me/) v.2.303 stable: It lists all installed apps, but sometimes cannot find Droid-ify 0.5.1

Now, I am well aware that this is not a very good bug report, but as you might have guessed, I do have a hard time really pinning the problem down and recreating it exactly ... one more thing though: these issues have only arisen with Droid-ify v.0.5.1, while v.0.4.9 worked without any issues I was aware of.

So, for the moment, I hope my report is enough to start the investigation. If anyone has suggestions and / or needs me to test something, I will do my best to do so.

Thanks so much in advance!
Thomas

**Comment by Iamlooker** [comment]
Can you contact me on telegram, I want to test an apk so we can fix this, because I don't have any Android 9 device.

**Comment by its-thomas** [comment]
Solution to the problem:

I did not consciously move "Droid-ify" to SD card, but the [recent 0.5.0 release](https://github.com/Iamlooker/Droid-ify/releases/tag/v0.5.0) had to be reinstalled for it to work and there – without me being aware of it or explicitly choosing it – it was installed on external sd storage. This obviously only happened on my Android 9 phone, but not on my Android 10 phone ...

Moving it back to internal storage has solved the problem :+1:
