### ISSUE TITLE
[BUG] OsmAnd

### ISSUE THREAD

**Issue by M1Aston** [Iamlooker/Droid-ify#218]
OsmAnd updates are not shown\detected or whatever.

 - Device: Xperia X
 - OS: Android 8
 - Version [e.g. v0.5.1]

**Comment by Iamlooker** [comment]
It looks like OsmAnd Maps and navigation have not set latest version as suggested. We cannot do anything, developers select which version to suggest to users. We shouldn't override it, you can set `Unstable Updates` to true to allow these updates to be visible
