### ISSUE TITLE
Proposal to add several new repos to the default list

### ISSUE THREAD

**Issue by balporig** [Iamlooker/Droid-ify#22]
- [fluffychat](https://fdroid.fluffychat.im/)
- [element-dev-fdroid](https://fdroid.krombel.de/element-dev-fdroid/)
- [element-dev-gplay](https://fdroid.krombel.de/element-dev-gplay/)
- [i2p](https://f-droid.i2p.io/repo/)
- [fdroidclient-nightly](https://gitlab.com/fdroid/fdroidclient-nightly/raw/master/fdroid/repo/)
- [CalyxOS Gitlab](https://calyxos.gitlab.io/calyx-fdroid-repo/fdroid/repo/) (different that the already existing one)
- [SimpleX Chat F-Droid](https://app.simplex.chat/fdroid/repo)
- [frostnerd](https://fdroid.frostnerd.com/fdroid/repo) for apps on [PublicAndroidApps · GitLab](https://git.frostnerd.com/PublicAndroidApps)
- [frostnerd archive](https://fdroidarchive.frostnerd.com/)
- [GitJournal](https://gitjournal.io/fdroid/repo/)

**Comment by Iamlooker** [comment]
Sure, plus I would like to a better way for you guys to select future default repositories.

Like a website or something where you can submit your favourite repositories.

**Comment by balporig** [comment]
Website sounds like a great idea. Also, combined with #19 will be just perfect. Probably besides the global backup and restore #19 there can be separate Import/Export for Repositories only.
