### ISSUE TITLE
[BUG] Disabling Material You theme causes the app to glitch.

### ISSUE THREAD

**Issue by MetaApo13** [Iamlooker/Droid-ify#223]
**Describe the bug**
Disabling Material You colour theme causes the app to glitch. 
The back button on the top bar of the settings screen stops working.

**To Reproduce**
1. Go to settings.
2. Click on the Material You option to enable it. 
3. Go back. Exit the app. Remove it from the RAM.
4. Open the app. Go to settings and disable the  Material You option.

**Expected behavior**
Material You theme should be disabled and the default theme should be enabled once again. 

**Demo Video**
https://user-images.githubusercontent.com/92925504/216242133-2a2ec9db-7066-4ff7-b5dc-c5a4cae4b217.mp4

**Smartphone:**
 - Device: Moto G52
 - OS: Android 12
 - Version: v 0.5.2

**Comment by Iamlooker** [comment]
I see it has something to do with `Incompatible versions`, if you disable it the issue will go away.

I will fix this is next Hotfix
