### ISSUE TITLE
[BUG] Block and removed by Google Play Protect

### ISSUE THREAD

**Issue by Brli** [Iamlooker/Droid-ify#230]
**Describe the bug**
Block and removed by Google Play Protect safety guard 

**To Reproduce**
1. Go to F-Droid
2. Search and install Droid-ify
3. Go to Play store
4. Scan for installed app
5. Got removed
6. Install the apk again
7. Warning of play store occurs

**Expected behavior**
Install normally 

**Screenshots**
![Screenshot_20230204-135156_Google_Play_Store.png](https://user-images.githubusercontent.com/4042566/216751470-3311ab89-0f24-4a93-b6e2-0f3918875fc4.png)

**Smartphone (please complete the following information):**
 - Device: [e.g. Pixel 6]
 - OS: [e.g. Android 12L]
 - Version [e.g. v0.5.1]

**Additional context**

While f-droid build server doesn't detect it?

**Comment by userkilled** [comment]
I see this system message for OsmAnd. 😁

**Comment by Brli** [comment]
Consider the fact that dozens of apps from F-droid has been installed on my
phone without this problem, this is not true that google remove packages
not signed by them.

linux2good ***@***.***> 於 2023年2月8日 週三 下午5:14 寫道：

**Comment by Iamlooker** [comment]
Can't fix
