### ISSUE TITLE
Bottom Navigation Bar is black

### ISSUE THREAD

**Issue by electr1fy0** [Iamlooker/Droid-ify#231]
It should be transparent.
Reference: https://developer.android.com/develop/ui/views/layout/edge-to-edge

**Comment by Iamlooker** [comment]
Provide more data please? What is your device and whats the android version.

They asked for a reason please give all the data. Use a issue template please.

**Comment by electr1fy0** [comment]
I'm sorry. I hope the following pictures make myself clear.

**Top**: Current Behaviour
**Bottom**: Proposed Behaviour


![current](https://user-images.githubusercontent.com/87616300/216821403-db8c72b1-98e4-418d-94e8-3766199399ba.png)
![preferred](https://user-images.githubusercontent.com/87616300/216821416-441fc6de-0865-4609-8727-4de83da769f7.png)

**Comment by Iamlooker** [comment]
And what is the android version of first screenshot?

**Comment by electr1fy0** [comment]
Android 13, Pixel 7.
The second screenshot is an edit.

**Comment by Iamlooker** [comment]
Seems like you are using 0.5.0 or 0.5.1

Edge to edge was added in v0.5.2 and v0.5.3. This update is not yet up on FDroid, so I would suggest downloading it from github if you can afford to reinstall the app. Or maybe wait for update on FDroid

**Comment by electr1fy0** [comment]
Wow, I can't believe I missed that.
The latest release indeed has Edge to Edge implemented. 
Thank You for that.

Again, I'm sorry for not following the template. 
I would have otherwise. It's just 95 percent of Android apps don't implement Edge to Edge (including many Google apps) makes me frustrated. I have done like 50 reports about this across different apps which is why I rushed it. 
I should have provided more detail.

**Comment by Iamlooker** [comment]
Its totally fine, enjoy the update 😉
