### ISSUE TITLE
Add romanian language

### ISSUE THREAD

**Issue by Alexandru51** [Iamlooker/Droid-ify#232]
Hello, i want to contribue to this app. And i want romanian language to be avalabile on hosted weblate.

**Comment by Iamlooker** [comment]
I have added new translation, you can start contributing [here](https://hosted.weblate.org/projects/droidify/localization/ro/)

**Comment by Alexandru51** [comment]
Hello, i did the translation

**Comment by Iamlooker** [comment]
In 2hrs 🤯

**Comment by Iamlooker** [comment]
In 2hrs 🤯
