### ISSUE TITLE
Can we please get the latest releases within the app?

### ISSUE THREAD

**Issue by steve51184** [Iamlooker/Droid-ify#236]
Can we please either get a custom repo or use one of the others so we can update the app within the app?

I know it's on there but there outdated from 2022 on f-droid server.. even izzy's is often old and outdated..

**Comment by Iamlooker** [comment]
In few upcoming releases I will add support for adding GitHub repos #18. We can add Droid-ify repo by default to it for faster updates

**Comment by steve51184** [comment]
Yeah I saw that post but it said it'd be added in 0.5.5 but that just released so was curious where you was at.. glad to here it's still planned all the best 👍🏻

**Comment by Iamlooker** [comment]
Ya few releases were pushed really quickly. I will try something until that release is done.

**Comment by Iamlooker** [comment]
Merge with #18 please
