### ISSUE TITLE
[BUG] Downloading an app plays the notification sound in a loop

### ISSUE THREAD

**Issue by opk12** [Iamlooker/Droid-ify#240]
**Describe the bug**
While an app is downloading, the phone emits the notification sound / vibration in a loop.

**To Reproduce**
- Click the green button to download an app (to be installed or updated).
- The phone now plays the system notification sound or vibration again and again, without stopping.
- When the download is finished, sounds and vibration are not played any more.

**Smartphone (please complete the following information):**
 - Device: Samsung
 - OS: Android 10
 - Version 0.5.1

**Additional context**
This does not happen on my Android 7.1 phone.
This must be a recent issue, I do not remember t happening on older versions.

**Comment by Iamlooker** [comment]
If you are not using the FDroid version of Droid-ify, can you try the same on 0.5.5?

Or maybe wait for FDroid update which will be available soon

**Comment by opk12** [comment]
It also happens on 0.5.5.

**Comment by Iamlooker** [comment]
Still happens on 0.5.6?

**Comment by Iamlooker** [comment]
@opk12 please respond

**Comment by opk12** [comment]
@Iamlooker F-droid is still is at 0.5.5

**Comment by opk12** [comment]
Still happens on 0.5.6.

**Comment by Iamlooker** [comment]
I can't reproduce this issue, I have cross-checked the code as well nut cannot find the issue.

Can you try setting `Silent` inside Droid-ify's Notification setting, check how to, over [here](https://www.androidpolice.com/how-to-set-an-android-apps-notifications-to-come-in-silent/).

You can safely silence all notifications as none are supposed to make sound anyways.

**Comment by Iamlooker** [comment]
https://user-images.githubusercontent.com/60404093/221838168-548a0ea8-c988-4ef2-85fd-46cb3578490f.mp4

Or try this

**Comment by opk12** [comment]
Thank you, silencing in the android settings solved it.
