### ISSUE TITLE
[BUG] App shows Installed for both F-Droid and Izzy's

### ISSUE THREAD

**Issue by yephny** [Iamlooker/Droid-ify#241]
**Describe the bug**
Apps that are both in Izzy's and F-Droid's repositories have the `installed` sign next to both repositories in the versions section.

**Expected behavior**
If there's a way for Droid-ify to differentiate between the two, I think the sign should appear next to only the repository the app's downloaded from.

**Smartphone**
 - OS: Android 10, LineageOS
 - Version 0.5.2.

**Comment by Iamlooker** [comment]
Can you share a screenshot please

**Comment by Iamlooker** [comment]
So, I think both of them might have the same signature. I will try to find a fix for this.

**Comment by yephny** [comment]
Yeah, they have the same signature. I suppose Droid-ify could keep track of what repository an app's downloaded from.

**Comment by yephny** [comment]
I compared [Myne](https://www.f-droid.org/packages/com.starry.myne/)'s signatures in App Manager, they match. It is found in F-Droid's list of [reproducible apps](https://gitlab.com/fdroid/fdroiddata/-/issues/2844).
