### ISSUE TITLE
[BUG] Changing sort mode is buggy

### ISSUE THREAD

**Issue by yephny** [Iamlooker/Droid-ify#248]
**Describe the bug**
With v.0.5.5, changing sort mode results in sort by Name, until you restart the app or open an app's page in Droid-ify.

**To Reproduce**
1. Change sort mode to something other than Name, as it already defaults to it.
2. You'll get a list sorted by name instead.
3. Open an app's page, then close it. You'll get the sorting of your choice.

**Expected behavior**
Just like in the previous versions, I expect that apps are sorted correctly as soon as I select my sorting of choice.

**Screenshots**
[A screen recording](https://i.imgur.com/Zai2gVB.mp4).

**Smartphone**
 - OS: Android 10, LineageOS
 - Version: v.0.5.5.

**Comment by Iamlooker** [comment]
Already fixed
