### ISSUE TITLE
Fix readme & izzyondroid logo

### ISSUE THREAD

**Issue by Bugaddr** [Iamlooker/Droid-ify#25]
Seems like due to some recent commits following logos got mismatched:

1) git repo readme
2) izzyondroid
3) f-droid.org

It may lead to confusion for user to decide the correct app, and since there is also neo store, almost identical it also increases confusion. A consistent logo design is need to be decided.

**Comment by Iamlooker** [comment]
I don't find anything misleading? Can you point out at something?

**Comment by Bugaddr** [comment]
> I don't find anything misleading? Can you point out at something?
> 
> Edit - The Icon in F-Droid will be updated after the push the new update

Yeah, the issue seems to be fixed but still the logo on the f-droid.org [1] doesn't match with app logo after installing [2]. 

1: fdroid
![IMG_20220712_001647.jpg](https://user-images.githubusercontent.com/99622785/178336775-a9033274-185b-408a-a4cd-a9dc93057b2b.jpg)

2: App logo
![IMG_20220712_001714.jpg](https://user-images.githubusercontent.com/99622785/178336949-88654624-3742-453d-829d-8bf02ec29aac.jpg)

This is easy fix i guess, you need to upload the new logo to f-droid.org. thanks

**Comment by Bugaddr** [comment]
> @Bugaddr, the logo for me is different to all of those... ![This depicts it.](https://user-images.githubusercontent.com/42837531/178339404-edb4112b-8fa4-4b91-9497-fce5ebefc26f.jpg)

Hey, sorry for confusing. Actually i had enabled izzyondroid in extra repo and as the algorithm of app it shows the latest updated app on top (for image & description) so its showing image from izzy. I think image on izzyondroid is different ? https://apt.izzysoft.de/fdroid/index/apk/com.looker.droidify

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
@IzzySoft, is your repository's metadata old? https://github.com/Iamlooker/Droid-ify/issues/25#issuecomment-1180750627

**Comment by IzzySoft** [comment]
Well, you have no `icon.png` in your Fastlane structure, so the one existing in my repo doesn't get replaced/updated automatically. Besides, the better place to look is [this one](https://apt.izzysoft.de/fdroid/index/apk/com.looker.droidify) :wink:

**Comment by IzzySoft** [comment]
Confirming the new icon having been picked up by my updater. Thanks!

![image](https://user-images.githubusercontent.com/6781438/178846239-345f24a1-5cea-454e-94af-ea0c52eed267.png)
