### ISSUE TITLE
Upgradable debug apk

### ISSUE THREAD

**Issue by NeeRaj-2401** [Iamlooker/Droid-ify#256]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when i have to update to latest debug apk but it fails and i have to make a clean installation (uninstalling previous debug).

**Describe the solution you'd like**
I guess the problem lies with the App signature. doesn't matches the previous and newly build apk.

**Additional context**
Few apps such as Libretube and innerTune have resolved this issue already.

**Comment by Iamlooker** [comment]
Yes, I know. They are debug builds for testing. And this is testing and there is no signing of apk on GitHub . If you are installing it from GitHub and testing with Android Studio as well, then this is expected.

**Comment by NeeRaj-2401** [comment]
> there is no signing of apk on GitHub

@Iamlooker there are [innerTune's implementation ](https://github.com/z-huang/music/commit/6586ff3ce1a145f42fd8d0bb8f731aa2706c770b)  & [LibreTube's approach ](https://github.com/libre-tube/LibreTube/pull/1639)

>They are debug builds for testing

I agree

>installing it from GitHub and testing with Android Studio

I personally do use latest debug's on my android device as regular because its more up to dated & also for testing purposes.

Anyways thanks :)

**Comment by Iamlooker** [comment]
Fixel by Daniel, I thought the isaue was with obselete module not with signing.
