### ISSUE TITLE
F-droid release.

### ISSUE THREAD

**Issue by KorneevVitaly** [Iamlooker/Droid-ify#26]
Glad Droid-ify returned. Will it be released or updated on F-droid?

**Comment by Iamlooker** [comment]
In #1 F-Droid build seems to fail. it is fixed now. So it might be available in coming days

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
I installed it via F-Droid during today. Does that mean that this should be closed?

**Comment by Iamlooker** [comment]
Yes
