### ISSUE TITLE
[BUG] Unable to remove the "Tap to install" notification by swiping even after app is installed

### ISSUE THREAD

**Issue by mecuricat** [Iamlooker/Droid-ify#261]
**Describe the bug**
When you download an app, you see an overlay to install the app as well as receive a notification saying "Downloaded <app name\>, Tap to install." After the app is installed, the notification is supposed to be removable by swiping. But it isn't.

**To Reproduce**
1. Open Droid-ify and download an app to install, let's say, [monocles browser](https://www.f-droid.org/packages/de.monocles.browser/).
2. Click the install button that appears.
3. After installation is complete, pull notification drawer and swipe to remove the install notification.
4. Notification cannot be swiped.

**Expected behavior**
Notification disappears.

**Screenshots**

https://user-images.githubusercontent.com/89805719/219750897-b6954735-a4ff-41e6-8b3f-4c2a22619747.mp4

**Smartphone (please complete the following information):**
 - Device: Redmi Note 10 Pro
 - OS: Android 12
 - Version 0.5.5

**Comment by Iamlooker** [comment]
This has been fixed already and will be available in next stable version
