### ISSUE TITLE
[BUG] "you have no internet connection" banner

### ISSUE THREAD

**Issue by Moxville** [Iamlooker/Droid-ify#262]
Device: Moto g82 5G
OS: Android 12
Version: 0.5.5

Every time I open the App, I see "you have no internet connection" banner.
But internet is working fine and no issues. I see the same issue in another old android phone as well

![Screenshot_20230217-224633](https://user-images.githubusercontent.com/31923265/219846805-76edf989-399b-4049-b859-dedf5975c0a0.png)

![IMG-20230218-WA0000](https://user-images.githubusercontent.com/31923265/219846821-de9bc160-42c3-4d2f-a54a-26c2abb97361.jpg)

**Comment by coxackie** [comment]
I can also confirm that it frequently appears...
