### ISSUE TITLE
[BUG] Button is not fully shown

### ISSUE THREAD

**Issue by d4f5409d** [Iamlooker/Droid-ify#265]
**Describe the bug**
We can't see the entire button.

**To Reproduce**
1. Go to Updates

**Expected behavior**
See the whole button

**Screenshots**
![Screenshot_2023-02-18-22-18-11-36_bf5286d428c97f865e4b51a5afbaefcd.jpg](https://user-images.githubusercontent.com/76624594/219900106-9294617a-2099-4a85-b3ab-701ceb4b1436.jpg)

**Smartphone (please complete the following information):**
 - Device: OnePlus 8
 - OS: Android 13
 - Version latest

**Additional context**

**Comment by bt90** [comment]
Same here on a Pixel 4a 5G with Android 13 and gesture navigation:

![Screenshot_20230309-123958.png](https://user-images.githubusercontent.com/1926175/224012902-23e409ba-27d4-46d8-bc69-ad6129ea997c.png)

**Comment by bt90** [comment]
The screen coordinates of the button are apparently calculated based on the moveable "Droidify" header. If the header is at the same height as the button bar, everything is displayed correctly:

![Screenshot_20230309-124507.png](https://user-images.githubusercontent.com/1926175/224013610-7602b36b-a20f-42e5-bb1d-e424bf9cb747.png)

**Comment by bt90** [comment]
@Iamlooker the moveable header seems more like a bug than a feature. At least i wouldn't want it to move while scrolling in the list.
