### ISSUE TITLE
[BUG] Cannot swipe between screenshots if zoomed in

### ISSUE THREAD

**Issue by mecuricat** [Iamlooker/Droid-ify#267]
**Describe the bug**
If I enlarge one of the screenshots of an app, I can no longer swipe to see adjacent screenshots.

**To Reproduce**
1. Open an app page in Droid-ify, let's say, [Just (Video) Player](https://www.f-droid.org/packages/com.brouken.player/).
2. Click on one of the screenshots and use two fingers or double tap to enlarge/zoom in.
3. Try swiping left or right.
4. Cannot swipe.

**Expected behavior**
Able to swipe left or right regardless of zooming in.

**Screenshots**

https://user-images.githubusercontent.com/112750975/219966677-b91e9631-894b-4ff9-b7f1-a5957fd43061.mp4

**Smartphone (please complete the following information):**
 - Device: Redmi Note 10 Pro
 - OS: Android 12
 - Version v0.5.5

**Comment by Iamlooker** [comment]
That is the intended behaviour. I will think about this but I cannot promise that this will be implemented
