### ISSUE TITLE
[Bug] Elements appear below the navigation bar

### ISSUE THREAD

**Issue by PandoraHayami** [Iamlooker/Droid-ify#27]
Before version 0.4.6, the "Show older versions" Button appeared just above the nav-bar, now it appears inside it. 

Before:
![Screenshot_20220708-124724](https://user-images.githubusercontent.com/79670265/178054765-fb8714d8-8394-4a33-bd69-15be2d75e6f3.png)
After:
![Screenshot_20220708-130055](https://user-images.githubusercontent.com/79670265/178054774-392ee0d7-dc4d-4178-9f1e-5fccc512531c.png)

**Comment by PandoraHayami** [comment]
Should've also said it happens on my phone, but I don't have a screenshot of the old version, it isn't that different tho.

**Comment by Iamlooker** [comment]
Can you please specify your Android Version

I cannot replicate this here

**Comment by balporig** [comment]
Can confirm the issue introduced with 0.4.6. All bottom content is now going under the navigation bar. I've tested it on Android 10 and 11. The issue is happens on 10 and not on 11.

**Comment by PandoraHayami** [comment]
Both of my devices are on Android 10, one is a LG Stylo 6 and another an Alcatel Joy Tab 2.

**Comment by Iamlooker** [comment]
I will try to fix this before next update. Sorry for the inconveniences

**Comment by Iamlooker** [comment]
I have two things to confirm

1. Are you not able to scroll down? I mean is that the max you can scroll to?
2. Is this also the case with settings page? I mean when you scroll max is this still happening?

**Comment by Iamlooker** [comment]
Huh weird this should not be happening, seems like an issue in the stdlib source code.

I will do a hotfix tonight and also report the bug to google.
