### ISSUE TITLE
[BUG] Update all button is to far down

### ISSUE THREAD

**Issue by GameOverFlowChart** [Iamlooker/Droid-ify#271]
**Describe the bug**
The update all button is to far at the bottom, cut out that you need to scroll to bring it completely to the screen, also the transparent navigation bar is on top of the the visible part until you scroll it up.

**To Reproduce**
1. Have 2-3 app which need an update
2. Go to updates tab

**Expected behavior**
The button is above the navigation bar and scrolling is disabled because everything fits on the page 

**Screenshots**
Sorry I don't have one at hand right now
Edit: same like this one
https://github.com/Iamlooker/Droid-ify/issues/271#issuecomment-1443203048

**Smartphone (please complete the following information):**
 - Device: [Realme]
 - OS: [Android 13]
 - Version [e.g. v0.5.6]

**Comment by GameOverFlowChart** [comment]
Update: I realize that the problem doesn't happen if in the setting the option to not make the top bar of the app dynamic is set than the button is at the right place. It seems like it's position is calculated based on the assumption that the bar isn't extended. And the app was most likely only tested with that setting enabled. I think this is a lesson for us: giving the option to change the gui with settings opens the door for new bugs.

**Comment by GameOverFlowChart** [comment]
Sidenote: That button doesn't disappear if no updates are available.

**Comment by ac130kz** [comment]
Same, the button is probably not a floating one.

![Screenshot_20230224-145137_Droid-ify](https://user-images.githubusercontent.com/24586896/221135054-7d251bad-0f60-40bf-9c16-3784dc4ac36c.png)

**Comment by GameOverFlowChart** [comment]
Seems like this is a duplicate of #265
I didn't see it or we made our bug report simultaneously .
