### ISSUE TITLE
[BUG] Wrong root request

### ISSUE THREAD

**Issue by HarriBuh** [Iamlooker/Droid-ify#275]
**Describe the bug**

Despite running in Shizuku mode, the app asks for root permission everytime I'm opening it- as long as I don't deny the request permanently that is.

**To Reproduce**

1. Open Droid-ify App 
2. Recognize root app asking for root permission

**Expected behavior**

Since I intentionally selected Shizuku- and not root-mode, the app must not ask for root privileges at all.

**Smartphone (please complete the following information):**

 - Device: Google Pixel 7
 - OS: Android 13
 - Version: latest of 0.5.6
Root and SUI installed & running

**Comment by Iamlooker** [comment]
I was asking for root permission when Shizuku was selected and asking for Shizuku when root was selected
