### ISSUE TITLE
Settings improvements

### ISSUE THREAD

**Issue by vertigo220** [Iamlooker/Droid-ify#277]
**Is your feature request related to a problem? Please describe.**
I've noticed a couple issues with the settings. First is with the "Clean up duration" one, which is unclear what it does. Second is the "Auto update apps" settings, which appears to have enabled/re-enabled itself.

**Describe the solution you'd like**
For the clean up duration setting, it would be nice to have a short description of what it does and, if I'm correct in assuming that it sets how often some sort of cleanup (of downloaded APKs?) is done, it should say "frequency" rather than "duration."

Regarding the auto update setting, I'm not sure if it's a new setting added in the most recent version (0.5.6) and was enabled by default or if it was there before and was enabled when the app was updated, but either way it's a problem, as it shouldn't default to auto-updating apps. Such a setting should always default to off and only be enabled by the user.

**Comment by vertigo220** [comment]
Hmm. My initial thought was to disagree, but I see your point. If the duration is 12h, that means it will be deleted 12h after being downloaded, hence duration, whereas frequency would suggest they're deleted _every_ 12h, which would mean an APK could be deleted after 12h if it's downloaded immediately after a cleanup, or after just a few minutes if it's downloaded right before a cleanup. Since it likely works in the former way, duration does make more sense, but I still think it's a poor name for the setting. Maybe something like "APK persistence" or "Clean up older than:" or something along those lines.

**Comment by GameOverFlowChart** [comment]
I don't mind if some explanation is provided somehow
