### ISSUE TITLE
[Bug] Droid-ify shows a generic advice despite "Ignore this version" is selected

### ISSUE THREAD

**Issue by serrq** [Iamlooker/Droid-ify#282]
When I select "ignore this version" for an app and then I update all repositories, Droid-ify displays a generic update notification.

Droid-ify 0.5.6 (f-droid) Android 12
OnePlus CPH2399

**Comment by Iamlooker** [comment]
Yes know, notification is behaving weirdly since last update.

**Comment by Iamlooker** [comment]
This has been fixed with previous commit 😄
