### ISSUE TITLE
[BUG] Switching app causes weird behaviour

### ISSUE THREAD

**Issue by Elbullazul** [Iamlooker/Droid-ify#284]
**Describe the bug**
When downloading an app, sometimes the download  freezes after switching to another app. Switching apps also bugs the action button, as it doesn't switch to "install" when the download is complete (the app also doesn't prompt to install)

**To Reproduce**
1. Open any app in the list (preferably one with a moderate/big APK size)
2. Click on "install"
3. Switch apps or go to the home screen
4. Switch back to Droid-ify

**Expected behavior**
The progress should continue updating when the app is focused again, and the button should switch to "install" when the download is finished.

**Screenshots**
[Video](https://streamable.com/zchfu3)

**Phone**
 - Device: Pixel 6 Pro
 - OS: Android 13 (Calyx OS)
 - Version: v0.5.6

**Comment by vertigo220** [comment]
For more context, this is the type of behavior I noted in #244.
