### ISSUE TITLE
[BUG] Crash on update 

### ISSUE THREAD

**Issue by Mylloon** [Iamlooker/Droid-ify#291]
**Describe the bug**
App is crashing when updating repos if a repo is invalid

**To Reproduce**
1. Add invalid repo, for example `https://codeberg.org/silkevicious/apkrepo/raw/branch/master/fdroid/repo`
2. Update
3. The app crash

**Expected behavior**
Should not crash

**Smartphone:**
 - Device: Mi Note 10 Lite
 - OS:  Android 12
 - Version: 0.5.6

**Comment by Iamlooker** [comment]
This has been fixed and will be available in next update on the weekend. Meanwhile you can test the alpha build on telegram

**Comment by Mylloon** [comment]
Okay! Thanks
