### ISSUE TITLE
[Feature] A way to export Favourites

### ISSUE THREAD

**Issue by Heus-Sueh** [Iamlooker/Droid-ify#295]
**Is your feature request related to a problem? Please describe.**
favourites will disappear if you uninstall the app

**Describe the solution you'd like**
a way to export them to a file (json, txt, xml...)

**Describe alternatives you've considered**
or save to cloud (nextcloud, google drive, dropbox...)

**Additional context**
.

**Comment by Iamlooker** [comment]
Merge with #19
