### ISSUE TITLE
[BUG] Animation

### ISSUE THREAD

**Issue by BabyOilJohnson** [Iamlooker/Droid-ify#296]
**Describe the bug**
When doing a smooth scroll through app page and home page the animation is showing weird.

**To Reproduce**
1. Scroll smoothly through the app page and homepage.

**Screenshots**
https://user-images.githubusercontent.com/101601874/224528488-8d71463d-5c77-4e61-8241-baa80b162ffc.mp4

**Smartphone (please complete the following information):**
 - Device: Samsung A30
 - OS: Android 11
 - Version v0.5.6

**Comment by Iamlooker** [comment]
Duplicate of #285
