### ISSUE TITLE
[BUG] Can't swipe screenshot

### ISSUE THREAD

**Issue by BabyOilJohnson** [Iamlooker/Droid-ify#298]
**Describe the bug**
I can't swipe screenshot for the first swipe, I have to swipe for second time to move.

**To Reproduce**
1. Go to app page
2. Click on a screenshot
3. Swipe to move to the next screenshot

**Expected behavior**
Screenshot should move to next for the first swipe.

**Smartphone (please complete the following information):**
 - Device: Samsung A30
 - OS: Android 11
 - Version v0.5.6

**Comment by Iamlooker** [comment]
Can't fix for now
