### ISSUE TITLE
Download all updates

### ISSUE THREAD

**Issue by mahdi1234** [Iamlooker/Droid-ify#3]
One thing really missing for many people in Foxy is "Download all". Would be great to either have a button to trigger it or to have a setting to auto download updates.

**Comment by Iamlooker** [comment]
Sure, Thats a great idea.
I was actually wondering what to do with this project.

**Comment by 3504k** [comment]
I believe this PR from Foxy would do this:

https://github.com/kitsunyan/foxy-droid/pull/101

I don't know the proper etiquette for listing this.

This comes from user @machiav3lli

**Comment by NoahAndrews** [comment]
It's really unfortunate that this project started with a fresh Git history, rather than starting from the Foxy Droid history.

**Comment by NoahAndrews** [comment]
Oh, you guys are working together now! I'll have to look into migrating the DHSM once your refactor is complete.

**Comment by mahdi1234** [comment]
Amazing, can't wait for new release :)
