### ISSUE TITLE
Hide outdated apps

### ISSUE THREAD

**Issue by Donkey-Doug** [Iamlooker/Droid-ify#30]
Add the option for a filter that can hide apps that have not received an update in x years/months.

Reason:
There are some VERY old apps on fdroid. I once tried one and it would not even launch on my modern android device anymore.
![Screenshot_20211015-030920_Droid-ify](https://user-images.githubusercontent.com/50382414/137416282-f1b7a1a2-0a12-4123-856a-e6c280c77c45.png)

**Comment by Iamlooker** [comment]
Well there are some people on ultra old phones, or a generic chinese phone/tablet
Which have lollipop or even kitkat so they might need those apps. :)

**Comment by Donkey-Doug** [comment]
perhaps an option in settings to not show apps that have not been updated in x days/months/years?
