### ISSUE TITLE
[BUG] color of titles appear to be using the wrong color

### ISSUE THREAD

**Issue by SnoutBug** [Iamlooker/Droid-ify#306]
**Describe the bug**
Droidify appears to be using a different color shade for titles contrary to whats usually used by other apps that implement material you.

For example:
- Lemuroid
- Connect You
- io.materialdesign.catalog

**Comment by Iamlooker** [comment]
This is done deliberately, because I wanted a specific color shade for each elements, and some issues have been fixed.
