### ISSUE TITLE
Animation occurs despite disablement of it.

### ISSUE THREAD

**Issue by BEEDELLROKEJULIANLOCKHART** [Iamlooker/Droid-ify#31]
Animation occurs despite disablement of it via the interface of this software and via the system-wide accessibility-toggle.

https://user-images.githubusercontent.com/42837531/178127598-613c5f35-7882-4952-b406-ac21ce1f1ebc.mp4

**Comment by Iamlooker** [comment]
Actually the setting is misrepresenting something else.

Animation it refers to is the animation of items in that list when you scroll.

**Comment by beedell-roke** [comment]
@Iamlooker, apologies for the confusion. I also have it disabled in `com.android.settings.Settings$DevelopmentSettingsDashboardActivity`:

~~~sh
#!/system/bin/sh
settings put global window_animation_scale 0.0     && \
settings put global transition_animation_scale 0.0 && \
settings put global animator_duration_scale 0.0    && \
reboot
~~~

**Comment by Iamlooker** [comment]
The swiping action which you are talking about is not actually a animation, its a view pager which means it is supposed to swipe with your finger.

**Comment by beedell-roke** [comment]
@Iamlooker, I was switching between them in the screencast via a tap, not swipe.

**Comment by beedell-roke** [comment]
> https://github.com/Droid-ify/client/issues/31#event-7007463090

@Iamlooker, this is an accessibility feature, and it also improves performance on old hardware. You should reconsider this.

**Comment by beedell-roke** [comment]
@Iamlooker, please re-close this as a duplicate of https://github.com/Droid-ify/client/issues/360#issue-1795389040.
