### ISSUE TITLE
[BUG] "GPS Video Logger" app won't install

### ISSUE THREAD

**Issue by vertigo220** [Iamlooker/Droid-ify#313]
**Describe the bug**
See title

**To Reproduce**
1. Go to GPS Video Logger app page
2. Click on Install
3. App downloads and shows pop-up asking to install, but clicking install causes it to act like it's installing but then it doesn't, and it goes back to showing the "Install" button instead of the "Launch" button that would show if it had installed

**Expected behavior**
App installs

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Samsung A71 5G UW
 - OS: [e.g. Android 13
 - Version v0.5.6

**Additional context**
Tried multiple times hours apart. Not sure if it's an issue with the app, with Droid-ify, or with my phone. Hopefully someone can either install it or repro the issue.

**Comment by vertigo220** [comment]
Tried in Neo Store and failed there, too. Both that and Droid-ify give "Unknown error. INSTALL_PARSE_FAILED_MANIFEST_MALFORMED: Failed parse during installPackage..." Also, can't even find the app on F-Droid, so I'm guessing that's the problem, though not sure why it's even showing up in Droid-ify and Neo Store.

**Comment by Iamlooker** [comment]
>  Also, can't even find the app on F-Droid, so I'm guessing that's the problem, though not sure why it's even showing up in Droid-ify and Neo Store.

Do you have Izzy4Droid added to your FDroid? As the app is available on Izzy4Droid.

**Comment by vertigo220** [comment]
Ah, no I don't, I only have the default ones. I did a search for Izz4Droid but Google only has four results. What's the url for it?

**Comment by meenbeese** [comment]
@vertigo220 Izzy4Droid is in the default list of repos in Droid-ify. You only have to go the repositories page and check the Izzy repo to activate it. Then refetch the apps and you're done!

**Comment by vertigo220** [comment]
I meant to add it to F-Droid so I could test the app there.
