### ISSUE TITLE
Suggestions and doubt

### ISSUE THREAD

**Issue by gallegonovato** [Iamlooker/Droid-ify#316]
Good afternoon @Iamlooker

First of all I apologize for not following the script of the suggestions but, I don't know what's wrong with me today I'm just messing myself up :(

Thank you for all your work and help.

I wanted to propose:

* If it is possible to translate the categories of the applications. I mean the one that appears in the drop down menu of all applications. I make this suggestion since there are people who use the application and do not get along well with English. And they comment me a lot that detail. And it could help them

* When there are several applications, you can click on a button and install them all. Instead of one by one. Or an option in the settings to disable or enable this option.

* Some applications do not show the icon. When the creator does. For example the application does not show the Acode icon but in https://github.com/deadlyjack/Acode (it comes out). Or for example Mull, Fennec, etc...

* Put in the sorted by part. The category of the favorite applications. Although the Favorites already have a separate section.

And the doubt:

* This already I see it complicated and for that this favorites. They comment to me if it would be possible to add some form to value the applications. Since this way it could help in the search of certain application to carry out a function. And this way you know that people are happy or recommend that application.  So according to what they tell me as something like Google Play Store.

A hug and I apologize for giving you so much trouble.

**Comment by Iamlooker** [comment]
> If it is possible to translate the categories of the applications. I mean the one that appears in the drop down menu of all applications. I make this suggestion since there are people who use the application and do not get along well with English. And they comment me a lot that detail. And it could help them

Sorry but this is not possible

> When there are several applications, you can click on a button and install them all. Instead of one by one. Or an option in the settings to disable or enable this option.

Parellel Downloader is in work, I am working on it.

> Some applications do not show the icon. When the creator does. For example the application does not show the Acode icon but in [deadlyjack/Acode](https://github.com/deadlyjack/Acode) (it comes out). Or for example Mull, Fennec, etc...

It might be because of the lack of fastlane support on the GitHub Repo of the respective apps

> Put in the sorted by part. The category of the favorite applications. Although the Favorites already have a separate section.

This is planned

> This already I see it complicated and for that this favorites. They comment to me if it would be possible to add some form to value the applications. Since this way it could help in the search of certain application to carry out a function. And this way you know that people are happy or recommend that application. So according to what they tell me as something like Google Play Store.

This is already informed in #2 , This will be worked on after v0.6.0.

I think I answered all the questions so I will be closing this issue. You can tag me if you want to reopen
