### ISSUE TITLE
[BUG] Cannot cancel download

### ISSUE THREAD

**Issue by haarp** [Iamlooker/Droid-ify#328]
**Describe the bug**
When an app download is triggered and stuck in the "Connecting..." state, the Cancel button is inoperative.

**To Reproduce**
1. Have shitty internet or wait until F-Droid repos are down (shouldn't take long :grin:)
2. Start app install
3. -> "Connecting..."
4. Press 'Cancel'
5. -> Nothing happens

**Expected behavior**
It should be possible to get out of this state without killing the app.

**Screenshots**
--

**Smartphone (please complete the following information):**
 - Device: Pixel 4
 - OS: Android 10
 - Version: 0.5.7

Thanks! :)

**Comment by Iamlooker** [comment]
Thats very weird, I will look into this

**Comment by haarp** [comment]
Nice, thanks a lot! :heart:
