### ISSUE TITLE
[BUG] Apps with no icon flicker

### ISSUE THREAD

**Issue by rhynec** [Iamlooker/Droid-ify#330]
**Describe the bug**
Apps which do not have an icon will flicker when switching between tabs and returning from search.

**To Reproduce**
1. Change tabs with an app with no icon in sight
2. Watch the default icon flicker

**Expected behavior**
It would be better if the default icon would remain static, even when searching but not finding a new icon

**Smartphone (please complete the following information):**
 - Device: Pixel 6a
 - OS: Android 13
 - Version: 0.5.7 (F-Droid)

**Comment by Iamlooker** [comment]
It is actually trying to fetch icon on internet while it is flickering. This feature is actually necessary, say you lost internet connection while it was loading and if it doesn't try refresh then it will always be showing error even if the icon is visible.

I will be closing this issue, but you can always tag me if you have a solution for this issue :)

**Comment by lokomoto** [comment]
I think the easiest fix would be if the request was successful but there is no icon returned, than use the default icon till Droid-ify restarts.

There are enough apps without icons, a special case being Julian's F-Droid Repo (Proton, GrapheneOS). This repo has no icons and wrongly reports several apps' update time as the current date and they are always shown between first. If you are active in the app, searching, scrolling, switching between tabs, opening apps to read description, this can easily result in dozens or even hundreds of requests.
