### ISSUE TITLE
Make repositories descriptions translatable

### ISSUE THREAD

**Issue by linux2good** [Iamlooker/Droid-ify#337]
Also, do not fetch description from server if repo is from the default list (not added by user), so it will not override translation.

**Comment by Iamlooker** [comment]
All the active repositories fetch descriptions from the index, which are localized in Index-v2 but not many repo's support it. So I don't think we need to make these translatable. I will be closing this issue for now but you can always tag me back to reopen this repo

**Comment by BLumia** [comment]
IndexV1 already contains localized data for displaying names and descriptions. I can submit a patch to add such support if you like. Can we reopen this issue?
