### ISSUE TITLE
 Which branch or tag should I merge for stable updates?

### ISSUE THREAD

**Issue by TheTanmay1** [Iamlooker/Droid-ify#338]
Hello, Droid-ify maintainers and contributors!

I'm interested in updating my fork of the Droid-ify repository and want to make sure I'm merging with the most stable branch or tag. Could you please provide guidance on which branch or tag I should merge with to ensure a stable experience?

Here's what I'm looking for:

The branch or tag name that represents the most recent stable release.
Any specific instructions or recommendations for merging, if applicable.
If there's a recommended method for staying updated on future stable releases, please let me know.
Thank you for your time and for your work on this project. I'm looking forward to contributing and staying up-to-date with Droid-ify's development.

**Comment by jcperil** [comment]
Please make general queries in [discussions](https://github.com/Iamlooker/Droid-ify/discussions).

**Comment by Iamlooker** [comment]
You can merge from main branch as it should be pretty stable or you can merge from the latest tag available
