### ISSUE TITLE
Share button for each application

### ISSUE THREAD

**Issue by sreeharimkl** [Iamlooker/Droid-ify#34]
I think it's important to have a share button for each applications in an appstore. An example is given below which is taken from fdroid official app.
![Screenshot_20211015-163705077_1](https://user-images.githubusercontent.com/50312757/137478234-7e48f905-4323-4163-a2b2-bc1ac2cd9e4c.jpg)

**Comment by Iamlooker** [comment]
I have a question.
Should it share the link on fdroid repo? (Because some apps are not on fdroid)
or Should it share link to app GitHub or GitLab page?

**Comment by Iamlooker** [comment]
This has been partially done.
Similar to what is on FDroid, it share links even if the app is unavailable on  FDroid Repo.

Check [here](https://github.com/Iamlooker/Droid-ify/commit/eb4f00711cc825132d53b3aec3aa26438370f103)

**Comment by sreeharimkl** [comment]
> This has been partially done. Similar to what is on FDroid, it share links even if the app is unavailable on FDroid Repo.
> 
> Check [here](https://github.com/Iamlooker/Droid-ify/commit/eb4f00711cc825132d53b3aec3aa26438370f103)

What about the direct download link copyable while holding down the version? Similar to copying the source link of the app
![Screenshot_20211030-181802978_1](https://user-images.githubusercontent.com/50312757/139533855-5a4dff71-1804-48e9-b8fd-3ca7f344d47d.jpg)

**Comment by Iamlooker** [comment]
I can implement this but links will only open in other fdroid client not on web app.

I think current implementation is the best, in next version u will get the last asked option to copy direct download link.

If you think this fixes the issue then you can close it otherwise please tell a work around.
