### ISSUE TITLE
[BUG] Hosted Weblate is currently broken

### ISSUE THREAD

**Issue by meenbeese** [Iamlooker/Droid-ify#344]
**Describe the bug**
An error must have occurred when Weblate tries to push translations to GitHub because it is now broken and does not accept any new contributions. It looks like manual intervention is needed from you to solve a merging conflict.

**To Reproduce**
1. Go to Hosted Weblate
2. Click on 'View Project Languages'
3. Scroll down to any language
4. Try to make a contribution
5. See the error that Weblate is locked

**Expected behavior**
Weblate should be working and open to any new contributions and translations.

**Screenshots**
![image](https://github.com/Iamlooker/Droid-ify/assets/114044633/b375fb5a-bd53-4271-8f60-273a33ca7fd5)

**Smartphone (please complete the following information):**
 - Device: not applicable
 - OS: not applicable
 - Version: not applicable

**Additional context**
This is the specific error that I get:
```
Rebasing (1/6)
Rebasing (2/6)
Rebasing (3/6)
Rebasing (4/6)
Rebasing (5/6)
error: could not apply d29f6047... Translated using Weblate (Vietnamese)
Resolve all conflicts manually, mark them as resolved with
"git add/rm <conflicted_files>", then run "git rebase --continue".
You can instead skip this commit: run "git rebase --skip".
To abort and get back to the state before "git rebase", run "git rebase --abort".
Could not apply d29f6047... Translated using Weblate (Vietnamese)
Auto-merging core/common/src/main/res/values-vi/strings.xml
CONFLICT (content): Merge conflict in core/common/src/main/res/values-vi/strings.xml
 (1)
```

**Comment by Iamlooker** [comment]
I don't know why this happened but I had to reset last 6 commits on weblate, which includes Serbian translation by @johndoe46682 on weblate
