### ISSUE TITLE
[Crash]

### ISSUE THREAD

**Issue by sms03** [Iamlooker/Droid-ify#346]
**Describe the bug**
The bug is whenever I open the app and go to my favourite app list and scroll down it crashes the app.

**To Reproduce**
1. Open 'droid-ify' app
2. Click on 'Three dots (on top right)'
3. Scroll down 'scrolling down crashes the app'
4. See error (app closes)

**Smartphone (please complete the following information):**
 - Device: [OnePlus Nord 2 5G]
 - OS: [Android 12]

**Comment by Iamlooker** [comment]
This has been fixed and will be available in next update
