### ISSUE TITLE
new app and recent updated app list option

### ISSUE THREAD

**Issue by nutpantz** [Iamlooker/Droid-ify#350]
Many fdroid apps have a list option for new apps added and recently updated apps. (Usually in last 2 weeks or so)

I use these features a lot to find new apps i did not know existed but need and yet they are activity developed. It's how i found droidify

**Comment by Iamlooker** [comment]
I think you want to sort apps list via "What's New" you can do that by clicking on three dots on top and then select "What's New" to see all newly added apps.
