### ISSUE TITLE
[Feature Request] RSS/Atom feed compatibility and notification for releases from various Git project repos

### ISSUE THREAD

**Issue by MysteriousOrb2000** [Iamlooker/Droid-ify#36]
I was wondering if we add the ability to import RSS feeds from various Git projects releases pages and the ability to download the APKs from the feed. This is for projects that don't use the F-droid repo structure. 

You would most likely have to add a warning that the user has to carefully choose the right APK to install based on the user's device and the project.

**Comment by Iamlooker** [comment]
Similar to #18 
Please merge both issues, i.e. continue the thread there
