### ISSUE TITLE
Silent install/update question

### ISSUE THREAD

**Issue by Offerel** [Iamlooker/Droid-ify#37]
Hi. According to what I understood, Droid-ify should be able to update apps from F-Droid automatically and without asking/manual interaction. Unfortunately this does not seem to work or I have misunderstood this. As a repository I currently have the normal F-Droid repository selected exclusively. I get a message that a new update for app xy is available, but the app is not updated automatically.

The phone does not have any root, but only the standard ROM of the manufacturer/carrier. Im on Android 12. How to enable automatic updates without manual interaction?

If this is currently not possible, is there a planned time, when this will be possible?

**Comment by Offerel** [comment]
Ahh ok. So currently there is no way without root. I thought there was a feature for Android 12 which allows silent/automatic install of updates outside of the playstore, which as possible with Droid-ify. 

Will this be possible in the future or do you know a alternative client which allows this? Currently i really like Droid-ify, because of its simplicity for the end-user and in-app performance. This is much better as the standard F-Droid client.

**Comment by GameOverFlowChart** [comment]
Silent install is an Android 12 feature and as far as I understand auto updates are a feature which requires silent install but also still needs to be implemented in droid-ify.

So what the request here is is a request for auto updates. And I want to add to this (not sure if I should open a new issue for that): auto updates should not happen if the update requires new permissions (maybe Android won't allow this?) or has new anti features (not sure if the app still has access to the anti features of the non actual version to compare).

**Comment by Offerel** [comment]
Exactly. For some reason I thought this was already implemented and wondered why it didn't work. Hence the question if there are already F-Droid clients that have this feature already implemented.

**Comment by Bugaddr** [comment]
> Silent install is an Android 12 feature and as far as I understand auto updates are a feature which requires silent install but also still needs to be implemented in droid-ify.
> 
> So what the request here is is a request for auto updates. And I want to add to this (not sure if I should open a new issue for that): auto updates should not happen if the update requires new permissions (maybe Android won't allow this?) or has new anti features (not sure if the app still has access to the anti features of the non actual version to compare).

Oh, i think there are some new api to implement that in a12. I think if you want that feature to be implemented in droid-ify you can start a new issue. Maybe provide a pr if you know how to do it. Thanks

**Comment by Bugaddr** [comment]
Btw this has been implemented in 14314a6cb3db5fa9364eb14b854b3a01400d99a7 check #14

**Comment by Offerel** [comment]
Unfortunately I don't have Android developer skills, otherwise I would have really liked to contribute a PR. But if I understand correctly, #14 refers only to the Shizuku service for pre-Android 12 devices. But maybe it fits for Android 12 and later as well. As I said, I'm not familiar with it unfortunately. Thanks for the link anyway.

**Comment by Bugaddr** [comment]
> Unfortunately I don't have Android developer skills, otherwise I would have really liked to contribute a PR. But if I understand correctly, #14 refers only to the Shizuku service for pre-Android 12 devices. But maybe it fits for Android 12 and later as well. As I said, I'm not familiar with it unfortunately. Thanks for the link anyway.

No problem :) . Btw please try new update if you can and test it on A12 maybe.

**Comment by Offerel** [comment]
Tried now all the installer types in 0.4.7 but none of them installed anything automatically.

Additionally the app is now in English, previous version was also available at least in german language. 

Ahh and when I select Shizuku installer, the app crashed, when I try to install an app for the first time.

**Comment by Iamlooker** [comment]
Actually the "Automatic Update" pitch by Google is nothing more than a illusion.

It says that if the User is on Android 12 than the App should target API 29 (i.e. Android 10)
And if User is on Android 12+ than the App being installed needs to target Android 11.

And even after that this will only allow Updates not Installs.

So in short, Droid-ify supports what is possible, Sadly I cannot do anything more than this 😢

And you need to restart the app for the Installer changes to take place, sorry that this was not prompted by app.

On this note I will be closing this issue

**Comment by Iamlooker** [comment]
You can read [this](https://developer.android.com/reference/android/content/pm/PackageInstaller.SessionParams#setRequireUserAction(int)) for more information

**Comment by Offerel** [comment]
Many thx for clarification. This explains some of the behavior.

But I'm a little confused about which installer to choose from. And I fear other user's are in the same boat. If i read all that, maybe it would be a wise idea to create a small matrix table as a wiki entryn on GitHub, where the user see clearly what he currently owns and can decide which installer to choose and what he can expect from that.

Maybe one column with the Android version as starting point another column with the installer type and a third column with what to expect.

Additionally I can think of a recommendation tag in the app itself, since I'm sure you can check in the app code, which Android version currently is in use 

But that's only a idea from someone how has no idea from Android development.

**Comment by GameOverFlowChart** [comment]
> Actually the "Automatic Update" pitch by Google is nothing more than a illusion.
> 
> It says that if the User is on Android 12 than the App should target API 29 (i.e. Android 10) And if User is on Android 12+ than the App being installed needs to target Android 11.
> 
> And even after that this will only allow Updates not Installs.
> 
> So in short, Droid-ify supports what is possible, Sadly I cannot do anything more than this 😢
> 
> And you need to restart the app for the Installer changes to take place, sorry that this was not prompted by app.
> 
> On this note I will be closing this issue

About silent installs:
I think that droid-ify supports silent installs is already great enough and that step from Google was also positive. Clicking on install silently installs the update. I'm not that much bothered that it only works for updates and only for "modern" Apps. This makes the app already much better than the official client.

About auto updates:
To make it clear, by auto update I mean that the app automatically launches the function that the button click on update and install (in the gui of droid-ify) would do. So the app would only need to "press" it's own buttons while in background. Does the app have less permissions while in background or why can't it do what it does in foreground after I press the button manually? Because for me it seems like all you need to do is press your own button programmatically while in background.

**Comment by Iamlooker** [comment]
> About auto updates:
> To make it clear, by auto update I mean that the app automatically launches the function that the button click on update and install (in the gui of droid-ify) would do. So the app would only need to "press" it's own buttons while in background. Does the app have less permissions while in background or why can't it do what it does in foreground after I press the button manually? Because for me it seems like all you need to do is press your own button programmatically while in background.

Well this does make a lot of sense I will try this and reply back.
