### ISSUE TITLE
[Feature Request] Make use of Github's milestone as a roadmap for Droidify

### ISSUE THREAD

**Issue by MysteriousOrb2000** [Iamlooker/Droid-ify#41]
https://github.com/Iamlooker/Droid-ify/milestones

I saw in another issue that you said you have a roadmap written down for what versions of Droidify would have new features added. It would be nice if you could display them on the roadmap.

**Comment by Iamlooker** [comment]
I was trying to find something to lay that on.

Lets try Milestones

**Comment by Iamlooker** [comment]
Ya this works thanks
