### ISSUE TITLE
exits on adding a new repo

### ISSUE THREAD

**Issue by ahmed-tasaly** [Iamlooker/Droid-ify#42]
_**Aloha there,**_

I installed **Droid-ify 3.0** 
Then **updated to 3.1**
..
After some time and adding some repos 
Something strange happened.

**Now on adding any new repo the application exits without adding it.**
I tried **rebooting the system clearing cache, data, reinstalling and using version 3.0**, but invain.
The only thing that can restore the functionality is **reverting to version 2.0**
Thanks in advance

**Comment by machiav3lli** [comment]
Redundant to #29
