### ISSUE TITLE
Navigation bar covers items 

### ISSUE THREAD

**Issue by oiao** [Iamlooker/Droid-ify#47]
First of all, thanks a lot for the awesome app, I enjoy it a lot. 

I've noticed that on my phone (Oneplus 6T, Android 10) the navigation bar seems to cover the last item in a list and it becomes tricky to select that. Is there any way to fix that? 

Many thanks! 

![Screenshot_20220717-205158~01](https://user-images.githubusercontent.com/29927996/179421394-4bcf146d-b233-4f06-b108-426fe30a41e7.jpg)

**Comment by Iamlooker** [comment]
This has been fixed. Please update to 0.4.7, if you are using FDroid version than wait for the update it should be up in one or two days 😄
