### ISSUE TITLE
App crashes when adding Bromite repository

### ISSUE THREAD

**Issue by twann4** [Iamlooker/Droid-ify#47]
**Describe the bug**
The app crashes when trying to add Bromite's repository.

**To Reproduce**

1. Click to add a new repository.
2. Try to add: `https://fdroid.bromite.org/fdroid/repo?fingerprint=E1EE5CD076D7B0DC84CB2B45FB78B86DF2EB39A3B6C56BA3DC292A5E0C3B9504`
3. See error

**Expected behavior**
The user should be able to add this repository.

**Smartphone (please complete the following information):**

- Device: SM-A310F
- OS: Android 10

**Additional context**
Here's the logcat: https://catbin.up.railway.app/irrogitina

**Comment by Iamlooker** [comment]
Similar to #29

**Comment by twann4** [comment]
Sorry, I didn't see it, I only searched for a similar issue under "Opened issues". 
Well, I can't wait for the next update ;)
