### ISSUE TITLE
New icon

### ISSUE THREAD

**Issue by julianfairfax** [Iamlooker/Droid-ify#48]
The new icon is worse than the previous icon in my opinion. Any chance of it being changed back?

**Comment by GameOverFlowChart** [comment]
I like it but maybe that's because I use dark theme.

**Comment by julianfairfax** [comment]
> I like it but maybe that's because I use dark theme. 

Yeah, I think that's why. It looks out of place with the light theme. Whereas the previous one looked good with both

**Comment by Iamlooker** [comment]
> The new icon is worse than the previous icon in my opinion. Any chance of it being changed back?

Well I am still don't feel settled on this icon
I want something more minimal than this, I mean something which is made of lines instead of a block

Although that's just my opinion 
And new submissions are always welcomed 😃

**Comment by julianfairfax** [comment]
> > The new icon is worse than the previous icon in my opinion. Any chance of it being changed back?
> 
> Well I am still don't feel settled on this icon
> I want something more minimal than this, I mean something which is made of lines instead of a block
> 
> Although that's just my opinion 
> And new submissions are always welcomed 😃

Is it not possible to go back to the old one in the meantime? Without dark mode this one looks really out of place

**Comment by GameOverFlowChart** [comment]
What about monochrome icons which will come with Android 13? I'm not sure how that will be for phones which still use Android 12 or lower.

**Comment by Iamlooker** [comment]
@GameOverFlowChart I don't think they will back port it to older versions

**Comment by julianfairfax** [comment]
So you're not going to do anything about an icon that only looks ok in dark mode? The previous icon was perfect. Why can't you keep using that? Or give an option in the settings to switch to it?
