### ISSUE TITLE
Remove empty space during search

### ISSUE THREAD

**Issue by rhynec** [Iamlooker/Droid-ify#49]
Currently, scrolling up during search will show the empty space that is usually used to show the app name. It look a bit out of place any time it happens. Would it be possible to prevent the empty space from showing during search?

![Screenshot_20220717-163510](https://user-images.githubusercontent.com/86078431/179427962-2c352ea3-602d-40d9-b1c6-7fd8831d8202.png)

**Comment by Iamlooker** [comment]
Can be merged with #32.
