### ISSUE TITLE
Can't change Installer 

### ISSUE THREAD

**Issue by yephny** [Iamlooker/Droid-ify#52]
**Describe the bug**
Only the system default package manager works for installing/uninstalling apps in Droid-ify. Installed Shizuku and tried out the installer using it. No difference. Switched to root installer, still uses the package manager. Never had this issue before version 0.4.7.

**Smartphone (please complete the following information):**
Android 10, LineageOS, Droid-ify v.0.4.7.

**Comment by Iamlooker** [comment]
You need to restart the all after changing the installer

**Comment by yephny** [comment]
@Iamlooker Thanks, it worked, but it still prompts the package manager when uninstalling apps through Droid-ify. I think it used to directly uninstall with root privileges before.

**Comment by Iamlooker** [comment]
Yes because I am yet to change the uninstaller
