### ISSUE TITLE
The new animations are a little distracting

### ISSUE THREAD

**Issue by OliverLew** [Iamlooker/Droid-ify#53]
Mainly how apps enter the view when scrolling. Of course, this is totally personal preference. Maybe an option to toggle animations?

Version: 0.3.2

**Comment by Donkey-Doug** [comment]
They are indeed annoying. Scrolling does not need an animation imo.

**Comment by another-sapiens** [comment]
I think toggles would be great for features like these, so it's opt-in for people who may like it
