### ISSUE TITLE
titlebar clipping

### ISSUE THREAD

**Issue by mininmobile** [Iamlooker/Droid-ify#53]
![Screenshot_20220719-123448_Droid-ify_1.png](https://user-images.githubusercontent.com/17964901/179742103-01f54ede-07d8-48a7-93d5-ced224a61c43.png)

i would expect the images to "flow" into the rounded corners of the title bar, instead of being clipped

**Comment by Iamlooker** [comment]
Actually this was expected because the implementation of rounded corner is not native. That means I am doing some hacking for this to work sooo.........

I have been trying to find fix for this and couldn't find any.

**Comment by Iamlooker** [comment]
Should I make the corners go away?

I mean its not really that good and its only bringing in issues

**Comment by mininmobile** [comment]
i like corner, but if there's no way to fix it it then i wouldn't mind if it was removed ¯\\\_(ツ)_/¯

**Comment by Iamlooker** [comment]
You can try 0.4.6 and check if you like
