### ISSUE TITLE
UI Improvements

### ISSUE THREAD

**Issue by dhishkyaon** [Iamlooker/Droid-ify#54]
Do not show application name on the top bar just like Foxy Droid. The application name is just under the top bar and it looks odd.

![Screenshot_20211020-201932.png](https://user-images.githubusercontent.com/88529066/138117850-2f6dc3f7-c17d-45c0-a880-bc45c27f7729.png)
![Screenshot_20211020-202009.png](https://user-images.githubusercontent.com/88529066/138117928-46426537-878a-4d7f-b560-607a4924d90b.png)

**Comment by dhishkyaon** [comment]
Then the 'Application' header should change to 'Application name' (for example Quotes here) after scrolling. At will look much better.

**Comment by dhishkyaon** [comment]
@Donkey-Doug thats an option too.

**Comment by another-sapiens** [comment]
I think a Settings section with toggles for all this visual stuff would be great for people who like the current UI.

**Comment by another-sapiens** [comment]
@dhishkyaon In that case, wouldn't the "Application" header also be redundant, as we already know it's an app?

IMO it's impossible to please everyone at the same time with visuals, hence the idea i proposed. 'Useless toggles' may come in handy in such situations, more so if they're tucked away and opt-in.
