### ISSUE TITLE
App not installed as package conflicts with another

### ISSUE THREAD

**Issue by helpthemfix** [Iamlooker/Droid-ify#6]
I have DivestOS which has Fdroid as a system App which I disabled. Since the reborn I can't install Droid-ify.

![f](https://user-images.githubusercontent.com/92321993/177546124-0e28b9d9-aacb-4afc-9f10-f986a172892c.png)

**Comment by Iamlooker** [comment]
Yes the signature is changed so you cannot update it directly. Its just a one time process, reinstall the app.

**Comment by helpthemfix** [comment]
My bad. I forgot I had it installed on the work profile. That caused the conflict. Thanks a lot!
