### ISSUE TITLE
Multiple Queue installation skips some apps installation using root.

### ISSUE THREAD

**Issue by PhoenixCODE2322** [Iamlooker/Droid-ify#61]
**Describe the bug**
When i start downloading 2 -3 apps simultaneously , there is mostly chance that one or two app won't get installed even though they were downloaded perfectly. Now when i come to that app again which did not installed and click on install , it gets installed instantly , it does not even download it .
Means the download was complete but install was not.

**To Reproduce**

1. Start downloading multiple apps.
2. Switch to other app.
3. Later come back and see some apps were not installed.

**Expected behavior**
All apps should have been installed

**Smartphone (please complete the following information):**

- Device: Realme 3 Pro
- OS: Android 12.1 Awaken OS ( Custom Rom)
- Version 0.4.7

**Additional context**
Itcs been happening for many releases, now it kind of became a problem.

**Suggestion**
Implementing a download queue /failed /pending list will fix this. So that user can see if something failed or is pending for installation and even a history where user tried to install an app but later either the user or the installation was cancelled.

Also one more thing please give a simple way to update many apps at a time . Currently we have to click on each app and starts its update.. Something similar to Aurora Droid would be good. Update all buttn and also a update button per app on right side for ease.

**Comment by Bugaddr** [comment]
Was it working as expected in any old version ?

**Comment by PhoenixCODE2322** [comment]
Naah .. there was always 1 or 2 app that would fail to install but download will be comepeleted.. Maybe it's my device . Thats why a dedicated history list would be good to see if some app are pending or not

**Comment by Bugaddr** [comment]
> Naah .. there was always 1 or 2 app that would fail to install but download will be comepeleted.. Maybe it's my device . Thats why a dedicated history list would be good to see if some app are pending or not

Oh ok thanks, i can produce the same bug. Seems like something in queue logic

**Comment by Iamlooker** [comment]
This should be fixed in this release
