### ISSUE TITLE
Fix author name in package info page

### ISSUE THREAD

**Issue by Bugaddr** [Iamlooker/Droid-ify#64]
In recent Ui changes to package info page the author name got default to "Source code" for all packages. It should display the name of package author as old updates.

1: Current
![IMG_20220728_010635_996.jpg](https://user-images.githubusercontent.com/99622785/181357557-27738a10-738e-426a-ade9-04ab2b6522b4.jpg)

2: Old
![IMG_20220728_010900_077.jpg](https://user-images.githubusercontent.com/99622785/181357801-ff63fe98-0872-4f88-809c-1b65a59fa50e.jpg)

**Comment by Iamlooker** [comment]
It was misleading as people would have thought it would point us at other apps from same developer.

I am currently working on refactoring database, It will allow us to add features with ease.
It will allow us to add better search query distinguishing and other features like Author searching, repository reordering, blacklisting, bookmarking and so on
