### ISSUE TITLE
Doubt with application

### ISSUE THREAD

**Issue by gallegonovato** [Iamlooker/Droid-ify#67]
Good afternoon:

It turns out that I use Autostarts from fdroid version 2.0.0 , but now in Droid-ify I get version 2.1.0 as you can see in this screenshot https://ibb.co/rv1zKM0

Appearing two. One from fdroid and one from github with veraion 2.0.0.0 and the new 2.1.0.

And with the same links to https://github.com/miracle2k/android-autostarts but I do not see this new version in the github.

I do not know if you could help me with this doubt if this new version is reliable. Or will it be released on fdroid?

Best regards and thanks for your time and help.

**Comment by Iamlooker** [comment]
It looks like somebody else took the flag

The package name is different for both apps and the new one looks like a fork of the old one, thats why you cannot find the release in the old repo 😉

**Comment by gallegonovato** [comment]
Good afternoon:

Thank you very much for all your work and effort. And for your help.

Thank you very much

Best regards
