### ISSUE TITLE
[BUG] Changing themes resets settings

### ISSUE THREAD

**Issue by user8446** [Iamlooker/Droid-ify#69]
Droid-ify v0.4.7

To reproduce:
1. Configure settings
2. Change the theme
3. Observe all configured settings are lost

Although there are not a lot of settings to configure, a user may not notice that their settings are lost.

Thank you

**Comment by Iamlooker** [comment]
Know and fixed already 😉

**Comment by Iamlooker** [comment]
Will be available in next rekeease

**Comment by user8446** [comment]
Great! Thank you for the development!
