### ISSUE TITLE
Version 0.3.4 launches with an oddly huge header

### ISSUE THREAD

**Issue by NoahAndrews** [Iamlooker/Droid-ify#69]
I don't mind the effect where the header expands when you scroll down at the top, I just dislike that it launches in that position.

![Screenshot_20211024-123301.png](https://user-images.githubusercontent.com/10224994/138605838-788661e4-2d2c-4d42-afd7-bc7639521a54.png)

**Comment by yephny** [comment]
How does being reachable have anything to do with this screen:
![img](https://a.pomf.cat/isranm.png)

**Comment by Iamlooker** [comment]
> How does being reachable have anything to do with the screen down below?

Imagine using s21 ultra at even lower dpi and then try approaching install button with one hand.

**Comment by yephny** [comment]
Honestly I don't see myself being unable to reach anywhere save for the corners even with that device in my hand. Though, it's super cool of you to be so considerate of one-handed people but isn't one-hand mode there just for this reason?
