### ISSUE TITLE
App Threema Libre

### ISSUE THREAD

**Issue by metzgerd** [Iamlooker/Droid-ify#70]
Hi,
Is it possible to install Threema Libre via Droid-ify? It's now available on F-Droid:
https://threema.ch/en/faq/libre_installation
Many thanks.

**Comment by itsmeralph09** [comment]
You can just add their F-droid repository in the Droid-ify repositories option.



![Screenshot_2022-08-11_12-29-49.png](https://user-images.githubusercontent.com/110166758/184064944-1f564d42-d007-430f-ba77-074dbf128ce0.png)

**Comment by Iamlooker** [comment]
Yes this should be working fine, Maybe I should document the app better on how to add repositories and other features.

**Comment by metzgerd** [comment]
Thank you. This helped.
