### ISSUE TITLE
Droid-ify has no share button in Droid-ify

### ISSUE THREAD

**Issue by yephny** [Iamlooker/Droid-ify#71]
**Describe the bug**
All apps in the official F-Droid repository have a share button, except for Droid-ify.

**Comment by Iamlooker** [comment]
Well I can see the share button, can you share s screenshot so I can confirm its not a `dpi` issue but a codebase issue

**Comment by yephny** [comment]
Strange, as now the button's there, along with the delete button. When I created this issue, only the settings button was visible.
