### ISSUE TITLE
Position while searching

### ISSUE THREAD

**Issue by HikaruIchijyo** [Iamlooker/Droid-ify#75]
Ok so do this.

Move through the apps then search anything  after result shown the position or it should show 1st app but it doesnt.

In simple words open droidify go through app list lets say u r on app number 20 search anything result should be shown from 1st app but it doesnt it still retains position to app no 20

**Comment by Iamlooker** [comment]
What would be the expected behaviour afterwards? Do you want it to scroll back to the previous position once the search query is cleared? Or do you want it to stay at 1st item even after the search query is cleared?

**Comment by HikaruIchijyo** [comment]
well i would suggest back to top  cuz scroll back to previous position would be hard
or maybe implement a floating button to move back to top or something like that?

**Comment by Iamlooker** [comment]
Ya, thats a good idea/point

**Comment by vertigo220** [comment]
+1. This has caused me to miss apps, thinking they're not in Droid-ify/F-Droid and switching to the Play Store (blech) to look for them. I'll do a search (or not), scroll down a ways, then do a different search and see that what I searched for isn't there, when in fact it was, I just had to scroll up. Doing the new search should have automatically jumped back to the top as part of refreshing the list. This applies not only to a whole new search but modifying the current search in any way.

**Comment by Iamlooker** [comment]
> well i would suggest to stay at top cuz scroll back to previous position would be hard implementation & design wise/animation wise it will be bad idk for sure though or maybe implement a floating button to move back to top or something like that?

A floating action button is implemented in the latest version. I will try to think of a good way to scroll to top when searching

**Comment by vertigo220** [comment]
> I will try to think of a good way to scroll to top when searching

I'd recommend simply resetting it (jumping to the top) whenever the contents of the search box are changed. Or you could make it like the Play Store where the search results are only updated when actually tapping the search button/icon, and have it scroll up then, though I think I kind of like the live search. The problem is, the live search and not scrolling up are a bad combination, because the results being updated as you type make you think you're seeing fully refreshed results, i.e. from the beginning, but you're really seeing refreshed results at your current position.

**Comment by Iamlooker** [comment]
I think the floating action button nicely indicates if we are at top position or not. I think this is fixed for now, if you disagree ping me here

**Comment by vertigo220** [comment]
@Iamlooker It does, but it's surprisingly easy to overlook that when your expectations are for it to behave a certain way, which in this case would be to scroll back up as the search is changed. Furthermore, I'd think that the majority of the time when you're changing the search, you'd want to scroll back up, so simply knowing you're not and then having to do so manually is an extra step and ultimately an obstacle to using the app. And if you do a search, scroll down, then change the search, it's almost certainly going to cause you to miss results if you don't scroll up. So I definitely think that just seeing that you're at a certain position isn't enough. It's like if you used a chat program and as the person you're chatting with wrote stuff to you, the scrollbar on the side changed to indicate there's more messages from them so you'd know to scroll down to see them. Almost nobody would like that, as they would expect it to auto-scroll to show those messages.

**Comment by Iamlooker** [comment]
Ooh scroll on search is also added I forgot to state
