### ISSUE TITLE
Exactly the screenshot tapped upon is not enlarged

### ISSUE THREAD

**Issue by uli-on** [Iamlooker/Droid-ify#79]
**Describe the bug**
All screenshots of an app are loaded and displayed, but the one tapped upon is not enlarged. The semi-transparent lightbox background is all there is. You can swipe to the left and to the right and view all other screenshots, but not the one you started the lightbox with.

**To Reproduce**

1. Open one app's detail page
2. Scroll to find the screenshots
3. Check that all of them are loaded by swiping the thumbnails
4. Tap upon one to enlarge it
5. Find it doesn't display
6. Swipe horizontally to view the other screenshots
7. Return to the tapped one and find its place empty still

**Smartphone (please complete the following information):**

- Fairphone 3
- Android v10 (8901.3.A.0136), upd. May 1, 2022, 
- GMS upd. later on to v22.24.13, 
- Webview v102.0.5005.78
- Droid-ify v0.4.7

**Additional context**
This might not happen each time and for every app viewed, which might have to do with image caching for apps already viewed today or some days before or in an earlier version of Droid-ify.

Happend for the first time in v0.4.7 or the version before.

Huge thanks for this lightning fast app, BTW!

**Comment by Iamlooker** [comment]
This is same as #40  but this seems like a better explanation and this will be fixed in next release.

Infact it is already fixed only building the apk is remaining.

**Comment by uli-on** [comment]
Thanks for the fix!
