### ISSUE TITLE
Redesign

### ISSUE THREAD

**Issue by Donkey-Doug** [Iamlooker/Droid-ify#80]
This is what flathub might look like soon. Flathub is an app store for linux. The design is really great, maybe do something similar for droidify?

https://user-images.githubusercontent.com/50382414/185766932-e47595f7-282c-4447-9579-6334d9a990e4.mp4

https://beta.flathub.org/

**Comment by HikaruIchijyo** [comment]
looks nice actually

**Comment by Iamlooker** [comment]
Personally I think this takes a lot of design hints from the design I made for Neo-Store but its ok.

I personally don't think we need to redesign our app at this point of time, I am working on Database side of work for now

Maybe in future but till then I am closing this issue. 😃
