### ISSUE TITLE
Way to keep downloaded "tap to install" notifications from appearing?

### ISSUE THREAD

**Issue by Pentaphon** [Iamlooker/Droid-ify#81]
Whenever I get say, 3 updates, I update each one successfully the app leaves all 3 notifications up in my notification shade. Can we get an option to keep those from appearing so we don't have to swipe them away all the time?

**Comment by Iamlooker** [comment]
This has already been fixed and will be available in next release

**Comment by Pentaphon** [comment]
> This has already been fixed and will be available in next release

What was the fix? I haven't seen any solution in 0.4.9
