### ISSUE TITLE
Barely visible nav buttons when using 0.4.8 on Stock Motorola firmware

### ISSUE THREAD

**Issue by Pentaphon** [Iamlooker/Droid-ify#82]
See screenshot. You can barely see the nav buttons at the bottom. I've seen this on a few other apps as well and they  were able to bring them back. 

![Screenshot_20220827-113343](https://user-images.githubusercontent.com/49374058/187043790-4b5e2848-547d-46dd-96a5-9a71c51ce2a9.png)

**Comment by Iamlooker** [comment]
Which Android version are you on?

**Comment by Pentaphon** [comment]
> Which Android version are you on?

11
