### ISSUE TITLE
Doubt with new function

### ISSUE THREAD

**Issue by gallegonovato** [Iamlooker/Droid-ify#84]
Good afternoon:

First of all thank you very much for your time and all your work. 

I have a question with the new Cleanup duration function. Since it gives the option to disable this option. But my doubt is that this will make the application start with the system or auto run itself after the set time. To make a cleaning I do not know if the repositories, cache or exactly that cleaning that would be due.

Then for example that nurva function is untranslated. It could be translated in several ways, depending on what the function does. For example:

Programar tiempo de limpieza
Programar limpieza
Programar limpieza automatica
Duracion de la limpieza ( It would be literal from English)

And inside the options are also not translated. They would be:

6 Horas
12 Horas
18 Horas
1 Día
2 Días

Then I looked inside the application to choose the type of installation. This can not lead to doubt which option to choose for non-expert users or not so expert users.

And I take this opportunity to comment on a bug in the new update. I already saw that a colleague commented https://github.com/Iamlooker/Droid-ify/issues/82 . This happens in several Samsung devices, Huawei, Oneplus also.

And if I may, I would like to propose a change. Since the black background of the application logo. It does not allow to admire well your logo. I think it would be better to put it transparent or white. And if you put transparent mark or increase the colors of the image. 

Please do not take my words and doubts wrong. It is not my intention to offend or anything bad. It is that your application is the best to continue having things from fdroid (for example), without having so many unnecessary permissions and anti-privacy that for example has the application of fdroid itself.

Best regards and thanks for your time and help.

**Comment by gallegonovato** [comment]
Good afternoon:

Thank you for your time and response.

Keeping an eye on this commit:
https://github.com/Iamlooker/Droid-i...cb50cb5154401c
We see the following:
val context = applicationContext
context.deleteOldIcons()
context.deleteOldReleases()
context.deletePartialFiles()
context.deleteTemporaryFiles()

I would say that it cleans old icons that appear in the startup listing, also obsolete releases, partial and temporary files (.apk or similar), etc.
I don't see it wrong so that the cache doesn't get triggered.


But this would force ls application, to perform a function that the phones already often bring (cleaning function) or other applications do as lte cleaner, sd maid ....

Or clean the cache and unnecessary things is a necessary thing in the operation of a mobile for me.

And the best thing about the application is that it does not start itself and keeps your privacy. And it has the right permissions, unlike fdroid itself. And also your application is wonderful for people with normal phones. And to start alone would be consuming some resources that the phone already does or other applications. Or musmo the user does or should do. Not to say that it is the best as I said.

About https://github.com/Iamlooker/Droid-ify/issues/82 happens on Android 11 and lineageos 17.1 or 18.1 . Thank you very much for fixing it in the next update.

I also noticed that the Fdroid Archive font does not synchronize. I do not know if it is a failure of the source. It seems to sync and download, but then comes out a warning that it could not sync Fdroid Archive.

Please do not take my words wrong. It is not my intention to do anything wrong. I just intebto help in what I know and I can, in an application that made me want more free code on mobile phones, without anything from Google and unnecessary permissions.

About the translation I will gladly help as much as I can.

The icon for me was better before, it looked cleaner and better. Or even an option could be just the image, marking the colors a little bit. In case it doesn't look good with a background image. But that's my honest opinion. 

A hug and thanks for your help and time.

**Comment by Iamlooker** [comment]
Well this function is necessary because otherwise the icons and other temp files are actually not temporary, they are permanent file to help with better stability.

Last release was in a hurry to fix the crash cause by #77

**Comment by gallegonovato** [comment]
Good afternoon @Iamlooker

Thanks for your time and help.

I have been making some translation suggestions. 

But I can't find that new function to translate.

It is still crashing when syncing Fdroid File.

A hug and thanks for your work and time.

**Comment by Iamlooker** [comment]
Did you update to 0.4.9?

**Comment by gallegonovato** [comment]
Good evening:

Bo I get the update in the application. But I looked at https://github.com/Iamlooker/Droid-ify/releases and I'm going to download it.

But it seems to be a bug in the source itself as Licaon_Kter comments.

But the rest goes perfectly.

A hug

**Comment by gallegonovato** [comment]
Good afternoon:

I don't know if I did well the translation of the application. 

In Hungarian SOCKS proxy I don't think it has translation. Not that I know

And then in Hindi translate from English Downloading %s... would be %s डाउनलोड हो रहा है... or %s daunalod ho raha hai.... 

Which I think gives error on the web because of the position of the percentage. The only thing I can think of would be to change to डाउनलोड हो रहा है %s... o daunalod ho raha hai %s ...

A hug

**Comment by gallegonovato** [comment]
Then about cleaning and updating. Maybe it makes a mess of the application. Because if they release a new version of x application. And the automatic update is activated. Well if you are doing cleaning and update ....

Or even if the automatic update is not active. But just at that moment you update. But the application is cleaning. Well...

Apart from that is what I said is launched or force the autostart at times throughout the day.

For example I put an example. A friend of mine uses Adaway and has active automatic updates. And he just has the Energized Hosts (for example). That are being updated very constantly throughout the day. Well, the battery was dropping because of this automatic update. I don't know if it will happen with the new Droid-ify option.

What I didn't find is that part to translate. If someone finds it would be in Spanish:

Ejecutar la liempieza ( It could be the most reasonable, although not literal English one.) . Programar limpieza (Idem above )
Programar limpieza automatica ( Idem above )
Duracion de la limpieza ( It would be literal from English)

6 Horas
12 Horas
18 Horas
1 Día
2 Días

A hug

**Comment by gallegonovato** [comment]
Good afternoon @Iamlooker

The translation page is missing parts of the application.

I am referring to the cleaning part. I pass screenshots for you to see that in the application is not translated:

https://ibb.co/Hx88zgn
https://ibb.co/7pPjhQM

A hug

**Comment by Iamlooker** [comment]
Translation will be available in the next update. Translation should be merged into source

**Comment by gallegonovato** [comment]
Good afternoon @Iamlooker 

Thank you for your reply.

But the curious thing is that in other languages that part is already available for translation.

For example in German, Finnish, French etc... There are 502 words and in Spanish 486.

Even if you open or create another language these new words come out...

Best regards

**Comment by Iamlooker** [comment]
I dont understand what you are trying to say, please elaborate

**Comment by gallegonovato** [comment]
Good afternoon:

I mean that in the web to translate it comes out in Spanish:

https://ibb.co/9V5sffC

But for example, Frances https://ibb.co/bFYYV5Y 

And in the translation web site you can see hours/hour, day/day for example to translate in all languages except Spanish.

As if there were missing words.

A hug

**Comment by Iamlooker** [comment]
@gallegonovato why are you adding translation in Roman in Hindi?

It was perfectly fine

**Comment by gallegonovato** [comment]
Good afternoon:

I am currently studying the language. Since they want to do business.

I apologize if something slipped through.

Best regards
