### ISSUE TITLE
Only sync when plugged in

### ISSUE THREAD

**Issue by haarp** [Iamlooker/Droid-ify#90]
There's an option to only sync on Wifi. Another option to only sync when plugged in (not running on battery) would be welcome aswell :)

Thanks!

**Comment by Donkey-Doug** [comment]
But syncing hardly uses any battery.

**Comment by Iamlooker** [comment]
Ya

**Comment by Iamlooker** [comment]
Added in 25fac9e77337c349a0581aec701d87a8214776ab

**Comment by haarp** [comment]
Nice, thanks a lot! :)
