### ISSUE TITLE
Requesting all translators

### ISSUE THREAD

**Issue by Iamlooker** [Iamlooker/Droid-ify#92]
## Please only translate in languages you personally speak or know really well.

A request to all translators, please refrain from overriding translations of other translators without talking with them. You can use discuss issues with each other in [Discussions page](https://github.com/Iamlooker/Droid-ify/discussions) on GitHub or simple leave a comment on the translation.

I looked into 17b3b17246e42c014447a21d73189e742cd76112 commit by @gallegonovato. He added translation in English Roman for Hindi language, which is also know as Hinglish in India.

I was personally able to locate this issue because I speak Hindi.

I request all the translator to look into the translation issue and correct them spontaneously. It is not urgent as next release will be a little late, but I would like to have it corrected before next release.

**Comment by gallegonovato** [comment]
Good afternoon:

I am currently studying the language. Since they want to do business.

I apologize if something slipped through.

Best regards
