### ISSUE TITLE
Integrate GitHub Projects' Release Notes

### ISSUE THREAD

**Issue by brezelman** [Iamlooker/Droid-ify#93]
Many apps are from GitHub and provide release notes only in the release details there. Would be cool, if Droid-ify extracted and displayed this information directly in the app.

**Comment by darlopvil** [comment]
Think the same. While it's not mandatory, it'd be nice to have an idea of what's going on.

**Comment by Iamlooker** [comment]
Sure I will add this to my todo but it is going to the later end of the list

**Comment by Iamlooker** [comment]
Merge with #18

**Comment by Iamlooker** [comment]
Both will be implemented together
