### ISSUE TITLE
Recently updated apps missing

### ISSUE THREAD

**Issue by msalini** [Iamlooker/Droid-ify#94]
v. 0.4.9 F-Droid

1. The recently-updated apps category seems to be missing from the list now
2. There is one extra category called "Sytem" containing just one app, and I think It has been included by mistake. (See screenshot)

![Screenshot_20220910-174153_Droid-ify](https://user-images.githubusercontent.com/32898857/189491315-b478d53f-b379-43a4-8f09-40ff27a1ad13.png)

**Comment by Iamlooker** [comment]
This is not controlled by Droid-ify, seems like someone made a typo in the FDroid team 😝

**Comment by msalini** [comment]
> This is not controlled by Droid-ify, seems like someone made a typo in the FDroid team 😝

And the missing category?

**Comment by Iamlooker** [comment]
Same, I can't do anything 'bout that

**Comment by Iamlooker** [comment]
Should I close this issue?
