### ISSUE TITLE
Can't install or update any apps

### ISSUE THREAD

**Issue by ahmedmahm0ud** [Iamlooker/Droid-ify#95]
**Ver. 0.4.9 from f-droid, and tried github apk
Android ver. 11 RKQ1.200826.002
Rom ver. MIUI Global 12.1.4 Stable**

repreduce the error
1. Update from 0.4.8 to 0.4.9 
2. Try update or install any app
3. Unknown Error
INSTALL_FAILED_INTERNAL_ERROR: Permission
Denied

Droid-ify have all the permissions it needed, and the permission to install apks also
![IMG_20220911_145519.jpg](https://user-images.githubusercontent.com/45968718/189528962-70fd8573-f0ea-4f2d-99f6-11fdc440dac7.jpg)

**Comment by Iamlooker** [comment]
If you are on MiUi, you have to use Legacy Installer instead of Session Installer.

**Comment by ahmedmahm0ud** [comment]
Thank you for helping, and for the great work of the project. 
Changing installer to legacy fixed my problem, but i hope if you can give me any sources to learn more about installer types on android and whats the diffrence between them and why miui use legacy installer to help me better understand and learn something new.
Thank you once agian for help, and i will close the issue
