### ISSUE TITLE
Android buttons are not visible

### ISSUE THREAD

**Issue by gallegonovato** [Iamlooker/Droid-ify#97]
In the latest version the Android buttons are not visible. If you have selected the theme: Clear, Amoled System, System.

I upload screen size https://ibb.co/G94GwR8

In lineageos 17.1, 18.1 and Android 11

A hug

**Comment by Iamlooker** [comment]
This has been fixed and will be available in next update.

**Comment by gallegonovato** [comment]
Good afternoon:

Thank you for your help and time.

Best regards
