### ISSUE TITLE
Older version is suggested

### ISSUE THREAD

**Issue by yephny** [Iamlooker/Droid-ify#99]
**Describe the bug**
An older version of K-9 Mail is suggested instead of the latest version available in F-Droid. There isn't even an update button, I can update the app only by tapping the latest version. `Ignore all new versions` is off.

**To Reproduce**

1. Go to K-9 mail in Droid-ify.
2. Scroll down to releases.

**Expected behavior**
I expect that the latest version of the app is suggested, as long as it is compatible with the device and not marked unstable.

**Screenshots**
![k9](https://a.pomf.cat/fcxems.png)

**Smartphone**
Droid-ify v.0.4.9 on LineageOS, Android 10.

**Comment by Mylloon** [comment]
aren't they pre-versions? have u non-stable updates checked in the settings?

**Comment by yephny** [comment]
@Mylloon They are pre-releases, which should be marked as such in F-Droid, yet they still show up even if `unstable updates` is off in Droid-ify settings.

**Comment by yephny** [comment]
I see, they show up regardless, the switch in the settings only changes whether pre-releases are suggested or not.
