### ISSUE TITLE
Screenshots take too much space

### ISSUE THREAD

**Issue by janTaja** [Iamlooker/Droid-ify#99]
When the app has a lot of screenshots, you have to scroll past all of them to see the description and other info. It would be better if they didn’t take a lot of space by default.

![Screenshot_20211030-222250_Droid-ify.jpg](https://user-images.githubusercontent.com/53832230/139556098-ff087a0f-c37c-492d-917e-72eaca9bc04e.jpg)

You could only show the first row and either have the button to expand screenshots below it (if there are more screenshots) or make it horizontally scrollable

**Comment by Donkey-Doug** [comment]
Duplicate https://github.com/Iamlooker/Droid-ify/issues/10
